namespace ZeldaFullEditor.ALTTP.GameData;
public record ItemReceiptName(int ID, string Name) : EntityName(ID, Name)
{
	public override string ToString() => $"{ID:X2} {Name}";

	public static readonly ItemReceiptName[] ListOfVanillaNames =
	{
		new(0x00, "Fighter sword"),
		new(0x01, "Master sword"),
		new(0x02, "Tempered sword"),
		new(0x03, "Butter sword"),
		new(0x04, "Fighter shield"),
		new(0x05, "Fire shield"),
		new(0x06, "Mirror shield"),
		new(0x07, "Fire rod"),
		new(0x08, "Ice rod"),
		new(0x09, "Hammer"),
		new(0x0A, "Hookshot"),
		new(0x0B, "Bow"),
		new(0x0C, "Boomerang"),
		new(0x0D, "Powder"),
		new(0x0E, "Bottle refill (bee)"),
		new(0x0F, "Bombos"),
		new(0x10, "Ether"),
		new(0x11, "Quake"),
		new(0x12, "Lamp"),
		new(0x13, "Shovel"),
		new(0x14, "Flute"),
		new(0x15, "Somaria"),
		new(0x16, "Bottle"),
		new(0x17, "Heart piece"),
		new(0x18, "Byrna"),
		new(0x19, "Cape"),
		new(0x1A, "Mirror"),
		new(0x1B, "Glove"),
		new(0x1C, "Mitts"),
		new(0x1D, "Book"),
		new(0x1E, "Flippers"),
		new(0x1F, "Pearl"),
		new(0x20, "Crystal"),
		new(0x21, "Net"),
		new(0x22, "Blue mail"),
		new(0x23, "Red mail"),
		new(0x24, "Small key"),
		new(0x25, "Compass"),
		new(0x26, "Heart container from 4/4"),
		new(0x27, "Bomb"),
		new(0x28, "3 Bombs"),
		new(0x29, "Mushroom"),
		new(0x2A, "Red boomerang"),
		new(0x2B, "Full bottle (red)"),
		new(0x2C, "Full bottle (green)"),
		new(0x2D, "Full bottle (blue)"),
		new(0x2E, "Potion refill (red)"),
		new(0x2F, "Potion refill (green)"),
		new(0x30, "Potion refill (blue)"),
		new(0x31, "10 Bombs"),
		new(0x32, "Big key"),
		new(0x33, "Map"),
		new(0x34, "1 Rupee"),
		new(0x35, "5 Rupees"),
		new(0x36, "20 Rupees"),
		new(0x37, "Green pendant"),
		new(0x38, "Blue pendant"),
		new(0x39, "Red pendant"),
		new(0x3A, "Tossed bow"),
		new(0x3B, "Silvers"),
		new(0x3C, "Full bottle (bee)"),
		new(0x3D, "Full bottle (fairy)"),
		new(0x3E, "Boss hc"),
		new(0x3F, "Sanc hc"),
		new(0x40, "100 Rupees"),
		new(0x41, "50 Rupees"),
		new(0x42, "Heart"),
		new(0x43, "Arrow"),
		new(0x44, "10 Arrows"),
		new(0x45, "Small magic"),
		new(0x46, "300 Rupees"),
		new(0x47, "20 Rupees green"),
		new(0x48, "Full bottle (good bee)"),
		new(0x49, "Tossed fighter sword"),
		new(0x4A, "Bottle refill (good bee)"),
		new(0x4B, "Boots"),

		//"Max Bombs(VT)",
		//"Max Arrows(VT)",
		//"Half Magic(VT)",
		//"Quarter Magic(VT)",
		//"L2 master Sword (VT)",
		//"+5 max bombs(VT)",
		//"+10 max bombs(VT)",
		//"+5 max arrows(VT)",
		//"+10 max arrows(VT)",
		//"Trap1(VT)",
		//"Trap2(VT)",
		//"Trap3(VT)",
		//"Silver Arrows(VT)",
		//"Rupoor(VT)",
		//"Null Item?(VT)",
		//"Red Clock(VT)",
		//"Blue Clock(VT)",
		//"Green Clock(VT)",
		//"Progressive Sword(VT)",
		//"Progressive Shield(VT)",
		//"Progressive Armor(VT)",
		//"Progressive Lifting Glove(VT)",
		//"RNG Pool Item (Single)(VT)",
		//"RNG Pool Item (Multi)(VT)" ,// 99
        //"","","","","","","",
		//"Goal Item (Single/Triforce)(VT)", //
        //"Goal Item (Multi/Power Star)(VT)", // 6B
        //"","","",
		//"Escape Map(VT)",
		//"Hyrule Castle Map(VT)",
		//"Eastern Map(VT)",
		//"Desert Map",
		//"Hyrule Castle2 Map(VT)",
		//"Swamp Map(VT)",
		//"Dark Map(VT)",
		//"Mire Map(VT)",
		//"Skull Map(VT)",
		//"Ice Map(VT)",
		//"Hera Map(VT)",
		//"Thieve Map(VT)",
		//"Turtle Map(VT)",
		//"GanonTower Map(VT)",
		//"??? Map(VT)",
		//"??? Map(VT)",
		//"Escape Compass(VT)",
		//"Hyrule Castle Compass(VT)",
		//"Eastern Compass(VT)",
		//"Desert Compass(VT)",
		//"Hyrule Castle2 Compass(VT)",
		//"Swamp Compass(VT)",
		//"Dark Compass(VT)",
		//"Mire Compass(VT)",
		//"Skull Compass(VT)",
		//"Ice Compass(VT)",
		//"Hera Compass(VT)",
		//"Thieve Compass(VT)",
		//"Turtle Compass(VT)",
		//"GanonTower Compass(VT)",
		//"??? Compass(VT)",
		//"??? Compass(VT)",
		//"Escape Big Key(VT)",
		//"Hyrule Castle Big Key(VT)",
		//"Eastern Big Key(VT)",
		//"Desert Big Key(VT)",
		//"Hyrule Castle2 Big Key(VT)",
		//"Swamp Big Key(VT)",
		//"Dark Big Key(VT)",
		//"Mire Big Key(VT)",
		//"Skull Big Key(VT)",
		//"Ice Big Key(VT)",
		//"Hera Big Key(VT)",
		//"Thieve Big Key(VT)",
		//"Turtle Big Key(VT)",
		//"GanonTower Big Key(VT)",
		//"??? Big Key(VT)",
		//"??? Big Key(VT)",
		//"Escape Key(VT)",
		//"Hyrule Castle Key(VT)",
		//"Eastern Key(VT)",
		//"Desert Key(VT)",
		//"Hyrule Castle2 Key(VT)",
		//"Swamp Key(VT)",
		//"Dark Key(VT)",
		//"Mire Key(VT)",
		//"Skull Key(VT)",
		//"Ice Key(VT)",
		//"Hera Key(VT)",
		//"Thieve Key(VT)",
		//"Turtle Key(VT)",
		//"GanonTower Key(VT)",
		//"??? Key(VT)",
		//"??? Key(VT)"
	};
}
