namespace ZeldaFullEditor.ALTTP.GameData;
public record OverworldScreenName(int ID, string Name) : EntityName(ID, Name)
{
	public override string ToString() => $"{ID:X2} {Name}";

	public static readonly OverworldScreenName[] ListOfVanillaNames =
	{
		new(0x00, "Lost Woods"),
		new(0x01, "Lost Woods"),
		new(0x02, "Lumberjacks"),
		new(0x03, "West Death Mountain"),
		new(0x04, "West Death Mountain"),
		new(0x05, "East Death Mountain"),
		new(0x06, "East Death Mountain"),
		new(0x07, "Turtle Rock Portalway"),
		new(0x08, "Lost Woods"),
		new(0x09, "Lost Woods"),
		new(0x0A, "Death Mountain Foot"),
		new(0x0B, "West Death Mountain"),
		new(0x0C, "West Death Mountain"),
		new(0x0D, "East Death Mountain"),
		new(0x0E, "East Death Mountain"),
		new(0x0F, "Waterfall of Wishing"),
		new(0x10, "Lost Woods Alcove"),
		new(0x11, "North of Kakariko"),
		new(0x12, "Northwest Pond"),
		new(0x13, "Sanctuary"),
		new(0x14, "Graveyard"),
		new(0x15, "Hylia River Bend"),
		new(0x16, "Potion Shop"),
		new(0x17, "Octorok Pit"),
		new(0x18, "Kakariko Village"),
		new(0x19, "Kakariko Village"),
		new(0x1A, "Kakariko Orchard"),
		new(0x1B, "Hyrule Castle"),
		new(0x1C, "Hyrule Castle"),
		new(0x1D, "Hylia River Peninsula"),
		new(0x1E, "Eastern Ruins"),
		new(0x1F, "Eastern Ruins"),
		new(0x20, "Kakariko Village"),
		new(0x21, "Kakariko Village"),
		new(0x22, "Smith's House"),
		new(0x23, "Hyrule Castle"),
		new(0x24, "Hyrule Castle"),
		new(0x25, "Boulder Field"),
		new(0x26, "Eastern Ruins"),
		new(0x27, "Eastern Ruins"),
		new(0x28, "Racing Game"),
		new(0x29, "South of Kakariko"),
		new(0x2A, "Haunted Grove"),
		new(0x2B, "West of Link's House"),
		new(0x2C, "Link's House"),
		new(0x2D, "Eastern Bridge"),
		new(0x2E, "Lake Hylia River Bend"),
		new(0x2F, "Eastern Portalway"),
		new(0x30, "Desert"),
		new(0x31, "Desert"),
		new(0x32, "Haunted Grove Entrance"),
		new(0x33, "Marshlands Portalway"),
		new(0x34, "Marshlands Totems"),
		new(0x35, "Lake Hylia"),
		new(0x36, "Lake Hylia"),
		new(0x37, "Lake Hylia River End"),
		new(0x38, "Desert"),
		new(0x39, "Desert"),
		new(0x3A, "Desert Pass"),
		new(0x3B, "Marshlands Dam Entrance"),
		new(0x3C, "Marshlands Ravine"),
		new(0x3D, "Lake Hylia"),
		new(0x3E, "Lake Hylia"),
		new(0x3F, "Lake Hylia Waterfall"),
		new(0x40, "Skull Woods"),
		new(0x41, "Skull Woods"),
		new(0x42, "Dark Lumberjacks"),
		new(0x43, "West Dark Death Mountain"),
		new(0x44, "West Dark Death Mountain"),
		new(0x45, "East Dark Death Mountain"),
		new(0x46, "East Dark Death Mountain"),
		new(0x47, "Turtle Rock"),
		new(0x48, "Skull Woods"),
		new(0x49, "Skull Woods"),
		new(0x4A, "Bumper Ledge"),
		new(0x4B, "West Dark Death Mountain"),
		new(0x4C, "West Dark Death Mountain"),
		new(0x4D, "East Dark Death Mountain"),
		new(0x4E, "East Dark Death Mountain"),
		new(0x4F, "Lake of Bad Omens"),
		new(0x50, "Skull Woods Alcove"),
		new(0x51, "North of Outcasts"),
		new(0x52, "Dark Northwest Pond"),
		new(0x53, "Dark Sanctuary"),
		new(0x54, "Dark Graveyard"),
		new(0x55, "Dark Hylia River Bend"),
		new(0x56, "Dark Northeast Shop"),
		new(0x57, "Dark Octorok Pit"),
		new(0x58, "Village of Outcasts"),
		new(0x59, "Village of Outcasts"),
		new(0x5A, "Outcasts Orchard"),
		new(0x5B, "Pyramid of Power"),
		new(0x5C, "Pyramid of Power"),
		new(0x5D, "Dark Hylia River Peninsula"),
		new(0x5E, "Palace of Darkness Maze"),
		new(0x5F, "Palace of Darkness Maze"),
		new(0x60, "Village of Outcasts"),
		new(0x61, "Village of Outcasts"),
		new(0x62, "Stake Puzzle"),
		new(0x63, "Pyramid of Power"),
		new(0x64, "Pyramid of Power"),
		new(0x65, "Boulder Field"),
		new(0x66, "Palace of Darkness Maze"),
		new(0x67, "Palace of Darkness Maze"),
		new(0x68, "Digging Game"),
		new(0x69, "South of Outcasts"),
		new(0x6A, "Stumpy Grove"),
		new(0x6B, "West of Bomb Shoppe"),
		new(0x6C, "Bomb Shoppe"),
		new(0x6D, "Hammer Bridge"),
		new(0x6E, "Dark Lake Hylia River Bend"),
		new(0x6F, "East Dark World Portalway"),
		new(0x70, "Misery Mire"),
		new(0x71, "Misery Mire"),
		new(0x72, "Stumpy Grove Entrance"),
		new(0x73, "Swamplands Portalway"),
		new(0x74, "Swamplands Totems"),
		new(0x75, "Dark Lake Hylia"),
		new(0x76, "Dark Lake Hylia"),
		new(0x77, "Dark Lake Hylia River End"),
		new(0x78, "Misery Mire"),
		new(0x79, "Misery Mire"),
		new(0x7A, "West of Swamplands"),
		new(0x7B, "Swamplands Palace Entrance"),
		new(0x7C, "Swamplands Ravine"),
		new(0x7D, "Dark Lake Hylia"),
		new(0x7E, "Dark Lake Hylia"),
		new(0x7F, "Dark Lake Hylia Waterfall"),
		new(0x80, "Master Sword Pedestal/Hobo bridge"),
		new(0x81, "Zora's Domain"),
		new(0x82, "Unused"),
		new(0x83, "Unused"),
		new(0x84, "Unused"),
		new(0x85, "Unused"),
		new(0x86, "Unused"),
		new(0x87, "Unused"),
		new(0x88, "Triforce room"),
		new(0x89, "Unused"),
		new(0x8A, "Unused"),
		new(0x8B, "Unused"),
		new(0x8C, "Unused"),
		new(0x8D, "Unused"),
		new(0x8E, "Unused"),
		new(0x8F, "Unused"),
		new(0x90, "Unused"),
		new(0x91, "Unused"),
		new(0x92, "Unused"),
		new(0x93, "Triforce room curtains"),
		new(0x94, "Hobo bridge shadow overlay"),
		new(0x95, "DM overlay"),
		new(0x96, "Pyramid background/No overlay"),
		new(0x97, "Grove fog overlay"),
		new(0x98, "Unused"),
		new(0x99, "Unused"),
		new(0x9A, "Unused"),
		new(0x9B, "Unused"),
		new(0x9C, "Dark DM overlay"),
		new(0x9D, "Woods fog overlay"),
		new(0x9E, "Lost woods clear overlay"),
		new(0x9F, "Rain"),
		//new(0xA0, "Unused"),
		//new(0xA1, "Unused"),
		//new(0xA2, "Unused"),
		//new(0xA3, "Unused"),
		//new(0xA4, "Unused"),
		//new(0xA5, "Unused"),
		//new(0xA6, "Unused"),
		//new(0xA7, "Unused"),
		//new(0xA8, "Unused"),
		//new(0xA9, "Unused"),
		//new(0xAA, "Unused"),
		//new(0xAB, "Unused"),
		//new(0xAC, "Unused"),
		//new(0xAD, "Unused"),
		//new(0xAE, "Unused"),
		//new(0xAF, "Unused"),
		//new(0xB0, "Unused"),
		//new(0xB1, "Unused"),
		//new(0xB2, "Unused"),
		//new(0xB3, "Unused"),
		//new(0xB4, "Unused"),
		//new(0xB5, "Garbage overlay"),
		//new(0xB6, "Unused"),
		//new(0xB7, "Unused"),
		//new(0xB8, "Unused"),
		//new(0xB9, "Unused"),
		//new(0xBA, "Unused"),
		//new(0xBB, "Unused"),
		//new(0xBC, "Unused"),
		//new(0xBD, "Unused"),
		//new(0xBE, "Garbage overlay that scrolls"),
		//new(0xBF, "Unused"),
		//new(0xC0, "Unused"),
		//new(0xC1, "Unused"),
		//new(0xC2, "Unused"),
		//new(0xC3, "Unused"),
		//new(0xC4, "Unused"),
		//new(0xC5, "Unused"),
		//new(0xC6, "Unused"),
		//new(0xC7, "Unused"),
		//new(0xC8, "Unused"),
		//new(0xC9, "Unused"),
		//new(0xCA, "Unused"),
		//new(0xCB, "Unused"),
		//new(0xCC, "Unused"),
		//new(0xCD, "Unused"),
		//new(0xCE, "Unused"),
		//new(0xCF, "Unused"),
		//new(0xD0, "Unused"),
		//new(0xD1, "Unused"),
		//new(0xD2, "Unused"),
		//new(0xD3, "Unused"),
		//new(0xD4, "Unused"),
		//new(0xD5, "Unused"),
		//new(0xD6, "Unused"),
		//new(0xD7, "Unused"),
		//new(0xD8, "Unused"),
		//new(0xD9, "Unused"),
		//new(0xDA, "Unused"),
		//new(0xDB, "Unused"),
		//new(0xDC, "Unused"),
		//new(0xDD, "Unused"),
		//new(0xDE, "Unused"),
		//new(0xDF, "Unused"),
		//new(0xE0, "Unused"),
		//new(0xE1, "Unused"),
		//new(0xE2, "Unused"),
		//new(0xE3, "Unused"),
		//new(0xE4, "Unused"),
		//new(0xE5, "Unused"),
		//new(0xE6, "Unused"),
		//new(0xE7, "Unused"),
		//new(0xE8, "Unused"),
		//new(0xE9, "Unused"),
		//new(0xEA, "Unused"),
		//new(0xEB, "Unused"),
		//new(0xEC, "Unused"),
		//new(0xED, "Unused"),
		//new(0xEE, "Unused"),
		//new(0xEF, "Unused"),
		//new(0xF0, "Unused"),
		//new(0xF1, "Unused"),
		//new(0xF2, "Unused"),
		//new(0xF3, "Unused"),
		//new(0xF4, "Unused"),
		//new(0xF5, "Unused"),
		//new(0xF6, "Unused"),
		//new(0xF7, "Unused"),
		//new(0xF8, "Unused"),
		//new(0xF9, "Unused"),
		//new(0xFA, "Unused"),
		//new(0xFB, "Unused"),
		//new(0xFC, "Unused"),
		//new(0xFD, "Unused"),
		//new(0xFE, "Unused"),
		//new(0xFF, "Unused"),
	};
}
