namespace ZeldaFullEditor.ALTTP.GameData;
public record RoomObjectName(int ID, string Name) : EntityName(ID, Name)
{
	public override string ToString() => $"{ID:X3} {Name}";

	public static readonly RoomObjectName[] ListOfSubtype1RoomObjects =
	{
		new(0x000, "Ceiling ↔"),
		new(0x001, "Wall (top, north) ↔"),
		new(0x002, "Wall (top, south) ↔"),
		new(0x003, "Wall (bottom, north) ↔"),
		new(0x004, "Wall (bottom, south) ↔"),
		new(0x005, "Wall columns (north) ↔"),
		new(0x006, "Wall columns (south) ↔"),
		new(0x007, "Deep wall (north) ↔"),
		new(0x008, "Deep wall (south) ↔"),
		new(0x009, "Diagonal wall A ◤ (top) ↔"),
		new(0x00A, "Diagonal wall A ◣ (top) ↔"),
		new(0x00B, "Diagonal wall A ◥ (top) ↔"),
		new(0x00C, "Diagonal wall A ◢ (top) ↔"),
		new(0x00D, "Diagonal wall B ◤ (top) ↔"),
		new(0x00E, "Diagonal wall B ◣ (top) ↔"),
		new(0x00F, "Diagonal wall B ◥ (top) ↔"),
		new(0x010, "Diagonal wall B ◢ (top) ↔"),
		new(0x011, "Diagonal wall C ◤ (top) ↔"),
		new(0x012, "Diagonal wall C ◣ (top) ↔"),
		new(0x013, "Diagonal wall C ◥ (top) ↔"),
		new(0x014, "Diagonal wall C ◢ (top) ↔"),
		new(0x015, "Diagonal wall A ◤ (bottom) ↔"),
		new(0x016, "Diagonal wall A ◣ (bottom) ↔"),
		new(0x017, "Diagonal wall A ◥ (bottom) ↔"),
		new(0x018, "Diagonal wall A ◢ (bottom) ↔"),
		new(0x019, "Diagonal wall B ◤ (bottom) ↔"),
		new(0x01A, "Diagonal wall B ◣ (bottom) ↔"),
		new(0x01B, "Diagonal wall B ◥ (bottom) ↔"),
		new(0x01C, "Diagonal wall B ◢ (bottom) ↔"),
		new(0x01D, "Diagonal wall C ◤ (bottom) ↔"),
		new(0x01E, "Diagonal wall C ◣ (bottom) ↔"),
		new(0x01F, "Diagonal wall C ◥ (bottom) ↔"),
		new(0x020, "Diagonal wall C ◢ (bottom) ↔"),
		new(0x021, "Platform stairs ↔"),
		new(0x022, "Rail ↔"),
		new(0x023, "Pit edge ┏━┓ A (north) ↔"),
		new(0x024, "Pit edge ┏━┓ B (north) ↔"),
		new(0x025, "Pit edge ┏━┓ C (north) ↔"),
		new(0x026, "Pit edge ┏━┓ D (north) ↔"),
		new(0x027, "Pit edge ┏━┓ E (north) ↔"),
		new(0x028, "Pit edge ┗━┛ (south) ↔"),
		new(0x029, "Pit edge ━━━ (south) ↔"),
		new(0x02A, "Pit edge ━━━ (north) ↔"),
		new(0x02B, "Pit edge ━━┛ (south) ↔"),
		new(0x02C, "Pit edge ┗━━ (south) ↔"),
		new(0x02D, "Pit edge ━━┓ (north) ↔"),
		new(0x02E, "Pit edge ┏━━ (north) ↔"),
		new(0x02F, "Rail wall (north) ↔"),
		new(0x030, "Rail wall (south) ↔"),
		new(0x031, "Nothing"),
		new(0x032, "Nothing"),
		new(0x033, "Carpet ↔"),
		new(0x034, "Carpet trim ↔"),
		new(0x035, "Weird door"), // TODO: WEIRD DOOR OBJECT NEEDS INVESTIGATION
		new(0x036, "Drapes (north) ↔"),
		new(0x037, "Drapes (west, odd) ↔"),
		new(0x038, "Statues ↔"),
		new(0x039, "Columns ↔"),
		new(0x03A, "Wall decors (north) ↔"),
		new(0x03B, "Wall decors (south) ↔"),
		new(0x03C, "Chairs in pairs ↔"),
		new(0x03D, "Tall torches ↔"),
		new(0x03E, "Supports (north) ↔"),
		new(0x03F, "Water edge ┏━┓ (concave) ↔"),
		new(0x040, "Water edge ┗━┛ (concave) ↔"),
		new(0x041, "Water edge ┏━┓ (convex) ↔"),
		new(0x042, "Water edge ┗━┛ (convex) ↔"),
		new(0x043, "Water edge ┏━┛ (concave) ↔"),
		new(0x044, "Water edge ┗━┓ (concave) ↔"),
		new(0x045, "Water edge ┗━┓ (convex) ↔"),
		new(0x046, "Water edge ┏━┛ (convex) ↔"),
		new(0x047, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x048, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x049, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x04A, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x04B, "Supports (south) ↔"),
		new(0x04C, "Bar ↔"),
		new(0x04D, "Shelf A ↔"),
		new(0x04E, "Shelf B ↔"),
		new(0x04F, "Shelf C ↔"),
		new(0x050, "Somaria path ↔"),
		new(0x051, "Cannon hole A (north) ↔"),
		new(0x052, "Cannon hole A (south) ↔"),
		new(0x053, "Pipe path ↔"),
		new(0x054, "Nothing"),
		new(0x055, "Wall torches (north) ↔"),
		new(0x056, "Wall torches (south) ↔"),
		new(0x057, "Nothing"),
		new(0x058, "Nothing"),
		new(0x059, "Nothing"),
		new(0x05A, "Nothing"),
		new(0x05B, "Cannon hole B (north) ↔"),
		new(0x05C, "Cannon hole B (south) ↔"),
		new(0x05D, "Thick rail ↔"),
		new(0x05E, "Blocks ↔"),
		new(0x05F, "Long rail ↔"),
		new(0x060, "Ceiling ↕"),
		new(0x061, "Wall (top, west) ↕"),
		new(0x062, "Wall (top, east) ↕"),
		new(0x063, "Wall (bottom, west) ↕"),
		new(0x064, "Wall (bottom, east) ↕"),
		new(0x065, "Wall columns (west) ↕"),
		new(0x066, "Wall columns (east) ↕"),
		new(0x067, "Deep wall (west) ↕"),
		new(0x068, "Deep wall (east) ↕"),
		new(0x069, "Rail ↕"),
		new(0x06A, "Pit edge (west) ↕"),
		new(0x06B, "Pit edge (east) ↕"),
		new(0x06C, "Rail wall (west) ↕"),
		new(0x06D, "Rail wall (east) ↕"),
		new(0x06E, "Nothing"),
		new(0x06F, "Nothing"),
		new(0x070, "Carpet ↕"),
		new(0x071, "Carpet trim ↕"),
		new(0x072, "Nothing"),
		new(0x073, "Drapes (west) ↕"),
		new(0x074, "Drapes (east) ↕"),
		new(0x075, "Columns ↕"),
		new(0x076, "Wall decors (west) ↕"),
		new(0x077, "Wall decors (east) ↕"),
		new(0x078, "Supports (west) ↕"),
		new(0x079, "Water edge (west) ↕"),
		new(0x07A, "Water edge (east) ↕"),
		new(0x07B, "Supports (east) ↕"),
		new(0x07C, "Somaria path ↕"),
		new(0x07D, "Pipe path ↕"),
		new(0x07E, "Nothing"),
		new(0x07F, "Wall torches (west) ↕"),
		new(0x080, "Wall torches (east) ↕"),
		new(0x081, "Wall decors tight A (west) ↕"),
		new(0x082, "Wall decors tight A (east) ↕"),
		new(0x083, "Wall decors tight B (west) ↕"),
		new(0x084, "Wall decors tight B (east) ↕"),
		new(0x085, "Cannon hole (west) ↕"),
		new(0x086, "Cannon hole (east) ↕"),
		new(0x087, "Tall torches ↕"),
		new(0x088, "Thick rail ↕"),
		new(0x089, "Blocks ↕"),
		new(0x08A, "Long rail ↕"),
		new(0x08B, "Jump ledge (west) ↕"),
		new(0x08C, "Jump ledge (east) ↕"),
		new(0x08D, "Rug trim (west) ↕"),
		new(0x08E, "Rug trim (east) ↕"),
		new(0x08F, "Bar ↕"),
		new(0x090, "Wall flair (west) ↕"),
		new(0x091, "Wall flair (east) ↕"),
		new(0x092, "Blue pegs ↕"),
		new(0x093, "Orange pegs ↕"),
		new(0x094, "Invisible floor ↕"),
		new(0x095, "Fake pots ↕"),
		new(0x096, "Hammer pegs ↕"),
		new(0x097, "Nothing"),
		new(0x098, "Nothing"),
		new(0x099, "Nothing"),
		new(0x09A, "Nothing"),
		new(0x09B, "Nothing"),
		new(0x09C, "Nothing"),
		new(0x09D, "Nothing"),
		new(0x09E, "Nothing"),
		new(0x09F, "Nothing"),
		new(0x0A0, "Diagonal ceiling A ◤"),
		new(0x0A1, "Diagonal ceiling A ◣"),
		new(0x0A2, "Diagonal ceiling A ◥"),
		new(0x0A3, "Diagonal ceiling A ◢"),
		new(0x0A4, "Pit ⇲"),
		new(0x0A5, "Diagonal layer 2 mask A ◤"),
		new(0x0A6, "Diagonal layer 2 mask A ◣"),
		new(0x0A7, "Diagonal layer 2 mask A ◥"),
		new(0x0A8, "Diagonal layer 2 mask A ◢"),
		new(0x0A9, "Diagonal layer 2 mask B ◤"), // TODO: VERIFY
		new(0x0AA, "Diagonal layer 2 mask B ◣"), // TODO: VERIFY
		new(0x0AB, "Diagonal layer 2 mask B ◥"), // TODO: VERIFY
		new(0x0AC, "Diagonal layer 2 mask B ◢"), // TODO: VERIFY
		new(0x0AD, "Nothing"),
		new(0x0AE, "Nothing"),
		new(0x0AF, "Nothing"),
		new(0x0B0, "Jump ledge (north) ↔"),
		new(0x0B1, "Jump ledge (south) ↔"),
		new(0x0B2, "Rug ↔"),
		new(0x0B3, "Rug trim (north) ↔"),
		new(0x0B4, "Rug trim (south) ↔"),
		new(0x0B5, "Archery game curtains ↔"),
		new(0x0B6, "Wall flair (north) ↔"),
		new(0x0B7, "Wall flair (south) ↔"),
		new(0x0B8, "Blue pegs ↔"),
		new(0x0B9, "Orange pegs ↔"),
		new(0x0BA, "Invisible floor ↔"),
		new(0x0BB, "Fake pressure plates ↔"),
		new(0x0BC, "Fake pots ↔"),
		new(0x0BD, "Hammer pegs ↔"),
		new(0x0BE, "Nothing"),
		new(0x0BF, "Nothing"),
		new(0x0C0, "Ceiling (large) ⇲"),
		new(0x0C1, "Chest platform (tall) ⇲"),
		new(0x0C2, "Layer 2 pit mask (large) ⇲"),
		new(0x0C3, "Layer 2 pit mask (medium) ⇲"),
		new(0x0C4, "Floor 1 ⇲"),
		new(0x0C5, "Floor 3 ⇲"),
		new(0x0C6, "Layer 2 mask (large) ⇲"),
		new(0x0C7, "Floor 4 ⇲"),
		new(0x0C8, "Water floor ⇲ "),
		new(0x0C9, "Flood water (medium) ⇲ "),
		new(0x0CA, "Conveyor floor ⇲ "),
		new(0x0CB, "Nothing"),
		new(0x0CC, "Nothing"),
		new(0x0CD, "Moving wall (west) ⇲"),
		new(0x0CE, "Moving wall (east) ⇲"),
		new(0x0CF, "Nothing"),
		new(0x0D0, "Nothing"),
		new(0x0D1, "Icy floor A ⇲"),
		new(0x0D2, "Icy floor B ⇲"),
		new(0x0D3, "Moving wall flag"), // TODO: WTF IS THIS?
		new(0x0D4, "Moving wall flag"), // TODO: WTF IS THIS?
		new(0x0D5, "Moving wall flag"), // TODO: WTF IS THIS?
		new(0x0D6, "Moving wall flag"), // TODO: WTF IS THIS?
		new(0x0D7, "Layer 2 mask (medium) ⇲"),
		new(0x0D8, "Flood water (large) ⇲"),
		new(0x0D9, "Layer 2 swim mask ⇲"),
		new(0x0DA, "Flood water B (large) ⇲"),
		new(0x0DB, "Floor 2 ⇲"),
		new(0x0DC, "Chest platform (short) ⇲"),
		new(0x0DD, "Table / rock ⇲"),
		new(0x0DE, "Spike blocks ⇲"),
		new(0x0DF, "Spiked floor ⇲"),
		new(0x0E0, "Floor 7 ⇲"),
		new(0x0E1, "Tiled floor ⇲"),
		new(0x0E2, "Rupee floor ⇲"),
		new(0x0E3, "Conveyor upwards ⇲"),
		new(0x0E4, "Conveyor downwards ⇲"),
		new(0x0E5, "Conveyor leftwards ⇲"),
		new(0x0E6, "Conveyor rightwards ⇲"),
		new(0x0E7, "Heavy current water ⇲"),
		new(0x0E8, "Floor 10 ⇲"),
		new(0x0E9, "Nothing"),
		new(0x0EA, "Nothing"),
		new(0x0EB, "Nothing"),
		new(0x0EC, "Nothing"),
		new(0x0ED, "Nothing"),
		new(0x0EE, "Nothing"),
		new(0x0EF, "Nothing"),
		new(0x0F0, "Nothing"),
		new(0x0F1, "Nothing"),
		new(0x0F2, "Nothing"),
		new(0x0F3, "Nothing"),
		new(0x0F4, "Nothing"),
		new(0x0F5, "Nothing"),
		new(0x0F6, "Nothing"),
		new(0x0F7, "Nothing"),
	};

	public static readonly RoomObjectName[] ListOfSubtype2RoomObjects =
	{
		new(0x100, "Corner (top, concave) ▛"),
		new(0x101, "Corner (top, concave) ▙"),
		new(0x102, "Corner (top, concave) ▜"),
		new(0x103, "Corner (top, concave) ▟"),
		new(0x104, "Corner (top, convex) ▟"),
		new(0x105, "Corner (top, convex) ▜"),
		new(0x106, "Corner (top, convex) ▙"),
		new(0x107, "Corner (top, convex) ▛"),
		new(0x108, "Corner (bottom, concave) ▛"),
		new(0x109, "Corner (bottom, concave) ▙"),
		new(0x10A, "Corner (bottom, concave) ▜"),
		new(0x10B, "Corner (bottom, concave) ▟"),
		new(0x10C, "Corner (bottom, convex) ▟"),
		new(0x10D, "Corner (bottom, convex) ▜"),
		new(0x10E, "Corner (bottom, convex) ▙"),
		new(0x10F, "Corner (bottom, convex) ▛"),
		new(0x110, "Kinked corner north (bottom) ▜"),
		new(0x111, "Kinked corner south (bottom) ▟"),
		new(0x112, "Kinked corner north (bottom) ▛"),
		new(0x113, "Kinked corner south (bottom) ▙"),
		new(0x114, "Kinked corner west (bottom) ▙"),
		new(0x115, "Kinked corner west (bottom) ▛"),
		new(0x116, "Kinked corner east (bottom) ▟"),
		new(0x117, "Kinked corner east (bottom) ▜"),
		new(0x118, "Deep corner (concave) ▛"),
		new(0x119, "Deep corner (concave) ▙"),
		new(0x11A, "Deep corner (concave) ▜"),
		new(0x11B, "Deep corner (concave) ▟"),
		new(0x11C, "Large brazier"),
		new(0x11D, "Statue"),
		new(0x11E, "Star tile (disabled)"),
		new(0x11F, "Star tile (enabled)"),
		new(0x120, "Small torch (lit)"),
		new(0x121, "Barrel"),
		new(0x122, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x123, "Table"),
		new(0x124, "Fairy statue"),
		new(0x125, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x126, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x127, "Chair"),
		new(0x128, "Bed"),
		new(0x129, "Fireplace"),
		new(0x12A, "Mario portrait"),
		new(0x12B, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x12C, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x12D, "Interroom stairs (up)"),
		new(0x12E, "Interroom stairs (down)"),
		new(0x12F, "Interroom stairs B (down)"),
		new(0x130, "Intraroom stairs north B"), // TODO: VERIFY LAYER HANDLING
		new(0x131, "Intraroom stairs north (separate layers)"),
		new(0x132, "Intraroom stairs north (merged layers)"),
		new(0x133, "Intraroom stairs north (swim layer)"),
		new(0x134, "Block"),
		new(0x135, "Water ladder (north)"),
		new(0x136, "Water ladder (south)"), // TODO: NEEDS IN GAME VERIFICATION
		new(0x137, "Dam floodgate"),
		new(0x138, "Interroom spiral stairs up (top)"),
		new(0x139, "Interroom spiral stairs down (top)"),
		new(0x13A, "Interroom spiral stairs up (bottom)"),
		new(0x13B, "Interroom spiral stairs down (bottom)"),
		new(0x13C, "Sanctuary wall (north)"),
		new(0x13D, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x13E, "Pew"),
		new(0x13F, "Magic bat altar"),
	};

	public static readonly RoomObjectName[] ListOfSubtype3RoomObjects =
	{
		new(0x200, "Waterfall face (empty)"),
		new(0x201, "Waterfall face (short)"),
		new(0x202, "Waterfall face (long)"),
		new(0x203, "Somaria path endpoint"),
		new(0x204, "Somaria path intersection ╋"),
		new(0x205, "Somaria path corner ┏"),
		new(0x206, "Somaria path corner ┗"),
		new(0x207, "Somaria path corner ┓"),
		new(0x208, "Somaria path corner ┛"),
		new(0x209, "Somaria path intersection ┳"),
		new(0x20A, "Somaria path intersection ┻"),
		new(0x20B, "Somaria path intersection ┣"),
		new(0x20C, "Somaria path intersection ┫"),
		new(0x20D, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x20E, "Somaria path 2-way endpoint"),
		new(0x20F, "Somaria path crossover"),
		new(0x210, "Babasu hole (north)"),
		new(0x211, "Babasu hole (south)"),
		new(0x212, "9 blue rupees"),
		new(0x213, "Telepathy tile"),
		new(0x214, "Warp door"), // TODO: NEEDS IN GAME VERIFICATION THAT THIS IS USELESS
		new(0x215, "Kholdstare's shell"),
		new(0x216, "Hammer peg"),
		new(0x217, "Prison cell"),
		new(0x218, "Big key lock"),
		new(0x219, "Chest"),
		new(0x21A, "Chest (open)"),
		new(0x21B, "Intraroom stairs south"), // TODO: VERIFY LAYER HANDLING
		new(0x21C, "Intraroom stairs south (separate layers)"),
		new(0x21D, "Intraroom stairs south (merged layers)"),
		new(0x21E, "Interroom straight stairs up (north, top)"),
		new(0x21F, "Interroom straight stairs down (north, top)"),
		new(0x220, "Interroom straight stairs up (south, top)"),
		new(0x221, "Interroom straight stairs down (south, top)"),
		new(0x222, "Deep corner (convex) ▟"),
		new(0x223, "Deep corner (convex) ▜"),
		new(0x224, "Deep corner (convex) ▙"),
		new(0x225, "Deep corner (convex) ▛"),
		new(0x226, "Interroom straight stairs up (north, bottom)"),
		new(0x227, "Interroom straight stairs down (north, bottom)"),
		new(0x228, "Interroom straight stairs up (south, bottom)"),
		new(0x229, "Interroom straight stairs down (south, bottom)"),
		new(0x22A, "Lamp cones"),
		new(0x22B, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x22C, "Liftable large block"),
		new(0x22D, "Agahnim's altar"),
		new(0x22E, "Agahnim's boss room"),
		new(0x22F, "Pot"),
		new(0x230, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x231, "Big chest"),
		new(0x232, "Big chest (open)"),
		new(0x233, "Intraroom stairs south (swim layer)"),
		new(0x234, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x235, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x236, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x237, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x238, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x239, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x23A, "Pipe end (south)"),
		new(0x23B, "Pipe end (north)"),
		new(0x23C, "Pipe end (east)"),
		new(0x23D, "Pipe end (west)"),
		new(0x23E, "Pipe corner ▛"),
		new(0x23F, "Pipe corner ▙"),
		new(0x240, "Pipe corner ▜"),
		new(0x241, "Pipe corner ▟"),
		new(0x242, "Pipe-rock intersection ⯊"),
		new(0x243, "Pipe-rock intersection ⯋"),
		new(0x244, "Pipe-rock intersection ◖"),
		new(0x245, "Pipe-rock intersection ◗"),
		new(0x246, "Pipe crossover"),
		new(0x247, "Bombable floor"),
		new(0x248, "Fake bombable floor"),
		new(0x249, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x24A, "Warp tile"),
		new(0x24B, "Tool rack"),
		new(0x24C, "Furnace"),
		new(0x24D, "Tub (wide)"),
		new(0x24E, "Anvil"),
		new(0x24F, "Warp tile (disabled)"),
		new(0x250, "Pressure plate"),
		new(0x251, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x252, "Blue peg"),
		new(0x253, "Orange peg"),
		new(0x254, "Fortune teller room"),
		new(0x255, "Unknown"), // TODO: NEEDS IN GAME CHECKING
		new(0x256, "Bar corner ▛"),
		new(0x257, "Bar corner ▙"),
		new(0x258, "Bar corner ▜"),
		new(0x259, "Bar corner ▟"),
		new(0x25A, "Decorative bowl"),
		new(0x25B, "Tub (tall)"),
		new(0x25C, "Bookcase"),
		new(0x25D, "Range"),
		new(0x25E, "Suitcase"),
		new(0x25F, "Bar bottles"),
		new(0x260, "Arrow game hole (west)"),
		new(0x261, "Arrow game hole (east)"),
		new(0x262, "Vitreous goo graphics"),
		new(0x263, "Fake pressure plate"),
		new(0x264, "Medusa head"),
		new(0x265, "4-way shooter block"),
		new(0x266, "Pit"),
		new(0x267, "Wall crack (north)"),
		new(0x268, "Wall crack (south)"),
		new(0x269, "Wall crack (west)"),
		new(0x26A, "Wall crack (east)"),
		new(0x26B, "Large decor"),
		new(0x26C, "Water grate (north)"),
		new(0x26D, "Water grate (south)"),
		new(0x26E, "Water grate (west)"),
		new(0x26F, "Water grate (east)"),
		new(0x270, "Window sunlight"),
		new(0x271, "Floor sunlight"),
		new(0x272, "Trinexx's shell"),
		new(0x273, "Layer 2 mask (full)"),
		new(0x274, "Boss entrance"),
		new(0x275, "Minigame chest"),
		new(0x276, "Ganon door"),
		new(0x277, "Triforce wall ornament"),
		new(0x278, "Triforce floor tiles"),
		new(0x279, "Freezor hole"),
		new(0x27A, "Pile of bones"),
		new(0x27B, "Vitreous goo damage"),
		new(0x27C, "Arrow tile ↑"),
		new(0x27D, "Arrow tile ↓"),
		new(0x27E, "Arrow tile →"),
		new(0x27F, "Nothing"),
	};
}
