namespace ZeldaFullEditor.ALTTP.GameData;
public record RoomName(int ID, string Name) : EntityName(ID, Name)
{
	public override string ToString() => $"{ID:X3} {Name}";

	public static readonly RoomName[] ListOfVanillaNames =
	{
		new(0x000, "Ganon fight"),
		new(0x001, "Hyrule Castle - Back"),
		new(0x002, "Hyrule Castle - sanctuary back"),
		new(0x003, "Houlihan room"),
		new(0x004, "Turtle Rock - Crystaroller"),
		new(0x005, "Empty room"),
		new(0x006, "Swamp Palace - Arrghus"),
		new(0x007, "Tower of Hera - Moldorm"),
		new(0x008, "Fairy east of Sanctuary - Top"),
		new(0x009, "Palace of Darkness - Shooter room"),
		new(0x00A, "Palace of Darkness - Stalfos basement"),
		new(0x00B, "Palace of Darkness - Monster truck room"),
		new(0x00C, "Ganon's Tower - Lobby"),
		new(0x00D, "Ganon's Tower - Agahnim 2"),
		new(0x00E, "Ice Palace - Entrance"),
		new(0x00F, "Empty room - Map Null"),
		new(0x010, "Ganon fight fall"),
		new(0x011, "Hyrule Castle - End of Sewers"),
		new(0x012, "Hyrule Castle - Sanctuary"),
		new(0x013, "Turtle Rock - Pokeys 1"),
		new(0x014, "Turtle Rock - Lava Pipes"),
		new(0x015, "Turtle Rock - Cold Pipes"),
		new(0x016, "Swamp Palace - Current room"),
		new(0x017, "Tower of Hera - Floor 5"),
		new(0x018, "Fairy east of Sanctuary - Bottom"),
		new(0x019, "Palace of Darkness - Dark maze"),
		new(0x01A, "Palace of Darkness - Falling bridge"),
		new(0x01B, "Palace of Darkness - Moving wall"),
		new(0x01C, "Ganon's Tower - Ice Armos"),
		new(0x01D, "Ganon's Tower - Penultima"),
		new(0x01E, "Ice Palace - Bombable floor"),
		new(0x01F, "Ice Palace - Penguin switch"),
		new(0x020, "Agahnim's Tower - Agahnim"),
		new(0x021, "Hyrule Castle - Sewers key rat"),
		new(0x022, "Hyrle Castle - Sewers rat party"),
		new(0x023, "Turtle Rock - Laser camp entrance"),
		new(0x024, "Turtle Rock - Big chest"),
		new(0x025, "Empty room"),
		new(0x026, "Swamp Palace - Switch statue"),
		new(0x027, "Tower of Hera - Floor 4"),
		new(0x028, "Swamp Palace - Lobby"),
		new(0x029, "Skull Woods - Mothula"),
		new(0x02A, "Palace of Darkness - Beetle arena"),
		new(0x02B, "Hookshot cave - Fairies"),
		new(0x02C, "Palace of Darkness - Sexy statue"),
		new(0x02D, "Room of Death"),
		new(0x02E, "Ice Palace - Penguins' chest"),
		new(0x02F, "Kakariko well"),
		new(0x030, "Agahnim's Tower - Sacrificial altar"),
		new(0x031, "Tower of Hera - Floor 3"),
		new(0x032, "Hyrule Castle - Sewers cross"),
		new(0x033, "Desert Palace - Lanmolas"),
		new(0x034, "Swamp Palace - West wing blocks"),
		new(0x035, "Swamp Palace - West wing flood"),
		new(0x036, "Swamp Palace - Big chest lobby"),
		new(0x037, "Swamp Palace - East wing flood"),
		new(0x038, "Swamp Palace - East wing hall"),
		new(0x039, "Skull Woods - Fall to boss"),
		new(0x03A, "Palace of Darkness - Main lobby"),
		new(0x03B, "Palace of Darkness - Hellway"),
		new(0x03C, "Hookshot cave - Booty room"),
		new(0x03D, "Ganon's Tower - Torches 2"),
		new(0x03E, "Ice Palace - Conveyor room"),
		new(0x03F, "Ice Palace - HP room"),
		new(0x040, "Agahnim's Tower - Cat walk"),
		new(0x041, "Hyrule Castle - Secret Sewers"),
		new(0x042, "Hyrule Castle - Sewers snake orgy"),
		new(0x043, "Desert Palace - Moving wall"),
		new(0x044, "Thieves' Town - Basement conveyors"),
		new(0x045, "Thieves' Town - Basement prison"),
		new(0x046, "Swamp Palace - Split O"),
		new(0x047, "Empty room"),
		new(0x048, "Empty room"),
		new(0x049, "Skull Woods - Torches"),
		new(0x04A, "Palace of Darkness - Entrance"),
		new(0x04B, "Palace of Darkness - Mimics warp"),
		new(0x04C, "Ganon's Tower - Bumpy conveyors"),
		new(0x04D, "Ganon's Tower - Moldorm 2"),
		new(0x04E, "Ice Palace - IPBJ"),
		new(0x04F, "Ice Palace - Clone with fairies"),
		new(0x050, "Hyrule Castle - West wing back"),
		new(0x051, "Hyrule Castle - Throne room"),
		new(0x052, "Hyrule Castle - East wing back"),
		new(0x053, "Desert Palace - Popo genocide"),
		new(0x054, "Swamp Palace - Pick a hole"),
		new(0x055, "Hyrule Castle - Secret tunnel"),
		new(0x056, "Skull Woods - West exit"),
		new(0x057, "Skull Woods - Statue puzzle"),
		new(0x058, "Skull Woods - Exploding wall"),
		new(0x059, "Skull Woods - Bridges"),
		new(0x05A, "Palace of Darkness - Helmasaur"),
		new(0x05B, "Ganon's Tower - Spike pegs"),
		new(0x05C, "Ganon's Tower - Cannon bridge"),
		new(0x05D, "Ganon's Tower - Gauntlets 1, 2, 3"),
		new(0x05E, "Ice Palace - Crossroads"),
		new(0x05F, "Ice Palace - Spiked floor"),
		new(0x060, "Hyrule Castle - East wing entrance"),
		new(0x061, "Hyrule Castle - Lobby"),
		new(0x062, "Hyrule Castle - West wing entrance"),
		new(0x063, "Desert Palace - Back entrance"),
		new(0x064, "Thieves' Town - Attic west"),
		new(0x065, "Thieves' Town - Attic east"),
		new(0x066, "Swamp Palace - Waterfalls"),
		new(0x067, "Skull Woods - Firebars"),
		new(0x068, "Skull Woods - Bumper room"),
		new(0x069, "Empty room"),
		new(0x06A, "Palace of Darkness - Dark rupees"),
		new(0x06B, "Ganon's Tower - Mimics fights"),
		new(0x06C, "Ganon's Tower - Lanmolas 2"),
		new(0x06D, "Ganon's Tower - Gauntlets 4, 5"),
		new(0x06E, "Ice Palace - Penguin lineup"),
		new(0x06F, "Empty room"),
		new(0x070, "Hyrule Castle - Prison airlock"),
		new(0x071, "Hyrule Castle - Guarded chests"),
		new(0x072, "Hyrule Castle - Basement entrance"),
		new(0x073, "Desert Palace - Big chest"),
		new(0x074, "Desert Palace - North hall"),
		new(0x075, "Desert Palace - Cannon hall"),
		new(0x076, "Swamp Palace - Drainage rooms"),
		new(0x077, "Tower of Hera - Lobby"),
		new(0x078, "Empty room"),
		new(0x079, "Empty room"),
		new(0x07A, "Empty room"),
		new(0x07B, "Ganon's Tower - Conveyor trolls"),
		new(0x07C, "Ganon's Tower - Falling basement bridge"),
		new(0x07D, "Ganon's Tower - Warp room A"),
		new(0x07E, "Ice Palace - Ice hall"),
		new(0x07F, "Ice Palace - Bari party"),
		new(0x080, "Hyrule Castle - Basement prison"),
		new(0x081, "Hyrule Castle - Basement bridge"),
		new(0x082, "Hyrule Castle - Basement pit"),
		new(0x083, "Desert Palace - West entrance"),
		new(0x084, "Desert Palace - Main lobby"),
		new(0x085, "Desert Palace - East entrance"),
		new(0x086, "Empty room"),
		new(0x087, "Tower of Hera - Floor 1"),
		new(0x088, "Empty room"),
		new(0x089, "Eastern Palace - Fairies"),
		new(0x08A, "Empty room"),
		new(0x08B, "Ganon's Tower - Pit block"),
		new(0x08C, "Ganon's Tower - Basement junction"),
		new(0x08D, "Ganon's Tower - Tile room puzzles"),
		new(0x08E, "Ice Palce - Blob party"),
		new(0x08F, "Empty room"),
		new(0x090, "Misery Mire - Vitreous"),
		new(0x091, "Misery Mire - Basement blobs"),
		new(0x092, "Misery Mire - Dark room pegs"),
		new(0x093, "Misery Mire - Dark room shooters"),
		new(0x094, "Empty room"),
		new(0x095, "Ganon's Tower - Falling guard bridge"),
		new(0x096, "Ganon's Tower - Torches 1"),
		new(0x097, "Mirey Mire - Moving wall"),
		new(0x098, "Misery Mire - Entrance"),
		new(0x099, "Eastern Palace - Dark eyegores"),
		new(0x09A, "Empty room"),
		new(0x09B, "Ganon's Tower - Warp room B"),
		new(0x09C, "Ganon's Tower - Invisible maze"),
		new(0x09D, "Ganon's Tower - E"),
		new(0x09E, "Ice Palace - Puzzle junction"),
		new(0x09F, "Ice Palace - Pottery hunt"),
		new(0x0A0, "Misery Mire - Penultima"),
		new(0x0A1, "Misery Mire - Fish room"),
		new(0x0A2, "Miser Mire - Bridges"),
		new(0x0A3, "Misery Mire - Waluigi bridge"),
		new(0x0A4, "Turtle Rock - Trinexx"),
		new(0x0A5, "Ganon's Tower - Wizzrobe fights"),
		new(0x0A6, "Ganon's Tower - Moldorm fall"),
		new(0x0A7, "Tower of Hera - Fairies"),
		new(0x0A8, "Eastern Palace - Stalfos room"),
		new(0x0A9, "Eastern Palace - Big chest"),
		new(0x0AA, "Eastern Palace - East hall"),
		new(0x0AB, "Thieves' Town - Spike room"),
		new(0x0AC, "Thieves' Town - Blind"),
		new(0x0AD, "Empty room"),
		new(0x0AE, "Ice Palace - Iced T"),
		new(0x0AF, "Ice Palace - Shittiest room"),
		new(0x0B0, "Agahnim's Tower - Circle of pots"),
		new(0x0B1, "Misery Mire - Hourglass"),
		new(0x0B2, "Misery Mire - Sluggula junction"),
		new(0x0B3, "Misery Mire - Spike chest"),
		new(0x0B4, "Turtle Rock - End of the line"),
		new(0x0B5, "Turtle Rock - Dark maze"),
		new(0x0B6, "Turtle Rock - Chomps"),
		new(0x0B7, "Turtle Rock - Roller chests"),
		new(0x0B8, "Eastern Palace - Antifairy chest"),
		new(0x0B9, "Eastern Palace - Cannon hall"),
		new(0x0BA, "Eastern Palace - Dark switch"),
		new(0x0BB, "Thieves' Town - Hellway"),
		new(0x0BC, "Thieves' Town - Toilet"),
		new(0x0BD, "Empty room"),
		new(0x0BE, "Ice Palace - Block switch"),
		new(0x0BF, "Ice Palace - Clone with switch"),
		new(0x0C0, "Agahnim's Tower - Dark pits"),
		new(0x0C1, "Misery Mire - Tile room"),
		new(0x0C2, "Misery Mire - Main lobby"),
		new(0x0C3, "Misery Mire - Falling bridge"),
		new(0x0C4, "Turtle Rock - Peg puzzle"),
		new(0x0C5, "Turtle Rock - Laser strip"),
		new(0x0C6, "Turtle Rock - Main lobby"),
		new(0x0C7, "Turtle Rock - Torch puzzle"),
		new(0x0C8, "Eastern Palace - Armos Knights"),
		new(0x0C9, "Eastern Palace - Entrance"),
		new(0x0CA, "Debug room"),
		new(0x0CB, "Thieves' Town - Northwest lobby"),
		new(0x0CC, "Thieves' Town - Northeast lobby"),
		new(0x0CD, "Empty room"),
		new(0x0CE, "Ice Palace - Fall to boss"),
		new(0x0CF, "Empty room"),
		new(0x0D0, "Agahnim's Tower - Dark maze"),
		new(0x0D1, "Misery Mire - Wall puzzle weekends"),
		new(0x0D2, "Misery Mire - Entry gauntlet"),
		new(0x0D3, "Empty room"),
		new(0x0D4, "Empty room"),
		new(0x0D5, "Turtle Rock - Laser bridge"),
		new(0x0D6, "Turtle Rock - Entrance"),
		new(0x0D7, "Empty room"),
		new(0x0D8, "Eastern Palace - Gauntlet"),
		new(0x0D9, "Eastern Palace - Cannon room"),
		new(0x0DA, "Eastern Palace - Upstairs antifairies"),
		new(0x0DB, "Thieves' Town - Southwest lobby"),
		new(0x0DC, "Thieves' Town - Southeast lobby"),
		new(0x0DD, "Empty room"),
		new(0x0DE, "Ice Palace - Kholdstare"),
		new(0x0DF, "Paradox Cave - Summit exit"),
		new(0x0E0, "Agahnim's Tower - Entrance"),
		new(0x0E1, "Lost Woods cave"),
		new(0x0E2, "Lumberjack Bumpkins' cave"),
		new(0x0E3, "Magic bat cave"),
		new(0x0E4, "Old Man's house cave"),
		new(0x0E5, "Old Man's house cave east"),
		new(0x0E6, "Death Mountain Descent - West"),
		new(0x0E7, "Death Mountain Descent - East"),
		new(0x0E8, "Superbunny cave - Top"),
		new(0x0E9, "Empty room"),
		new(0x0EA, "Spectacle Rock cave - Top"),
		new(0x0EB, "Bumper cave - Top"),
		new(0x0EC, "Empty room"),
		new(0x0ED, "Death Mountain fairy cave - Top"),
		new(0x0EE, "Spiral cave - top"),
		new(0x0EF, "Paradox cave - Moldorm chests"),
		new(0x0F0, "Lost Old Man's cave - West"),
		new(0x0F1, "Lost Old Man's cave - East"),
		new(0x0F2, "Sahasrahla's house - West"),
		new(0x0F3, "Sahasrahla's house - East"),
		new(0x0F4, "Feuding brothers - West"),
		new(0x0F5, "Feuding brothers - East"),
		new(0x0F6, "Empty room"),
		new(0x0F7, "Empty room"),
		new(0x0F8, "Superbunny cave - Bottom"),
		new(0x0F9, "Spectacle Rock cave - Bottom, west"),
		new(0x0FA, "Spectacle Rock cave - Bottom, East"),
		new(0x0FB, "Bumper cave - Bottom"),
		new(0x0FC, "Empty room"),
		new(0x0FD, "Death Mountain fairy cave - Bottom"),
		new(0x0FE, "Spiral cave - Bottom"),
		new(0x0FF, "Paradox cave - Shop"),
		new(0x100, "Boring chest game"),
		new(0x101, "Kakariko houses"),
		new(0x102, "Sick kid's house"),
		new(0x103, "Kakariko hospitality facilities"),
		new(0x104, "Link's house"),
		new(0x105, "Sahasrahlah's hideout"),
		new(0x106, "Fun chest game"),
		new(0x107, "Library and secret pots"),
		new(0x108, "Chicken hut"),
		new(0x109, "Potion shop"),
		new(0x10A, "Aginah's hideout"),
		new(0x10B, "Dam control room"),
		new(0x10C, "Mimic cave"),
		new(0x10D, "Mire shed"),
		new(0x10E, "Two hints"),
		new(0x10F, "Dark World shop"),
		new(0x110, "Dark World shop"),
		new(0x111, "Arrow game"),
		new(0x112, "Dark sanc and shop"),
		new(0x113, "King's tomb"),
		new(0x114, "Waterfall fairy and Watto"),
		new(0x115, "Pond of Happiness"),
		new(0x116, "Fat Fairy"),
		new(0x117, "Spike Cave"),
		new(0x118, "Unfun chest game"),
		new(0x119, "Blind's hideout - Upstairs"),
		new(0x11A, "Broccoli's hideout"),
		new(0x11B, "Grove and Grave caves"),
		new(0x11C, "Bomb shop and C-house"),
		new(0x11D, "Blind's hideout - Basement"),
		new(0x11E, "Fairies and Thief cave"),
		new(0x11F, "Not notable shop"),
		new(0x120, "Ice cave"),
		new(0x121, "Dwarven smithery"),
		new(0x122, "Fortune Tellers x2"),
		new(0x123, "Mini moldorm cave"),
		new(0x124, "Rich pots and Bonk rocks"),
		new(0x125, "Small rupee cache and Mini spike cave"),
		new(0x126, "Big fairy and Checkerboard cave"),
		new(0x127, "Stake puzzle and unused spike cave"),
	};

}
