namespace ZeldaFullEditor.ALTTP.GameData;

public record TileTypeName(int ID, string Name) : EntityName(ID, Name)
{
	public override string ToString() => $"{ID:X2} {Name}";

	public static readonly TileTypeName[] ListOfVanillaNames =
	{
		new(0x00, "Nothing (standard floor)"),
		new(0x01, "Collision"),
		new(0x02, "Collision"),
		new(0x03, "Collision"),
		new(0x04, "Collision"),
		new(0x05, "Nothing"),
		new(0x06, "Nothing"),
		new(0x07, "Nothing"),
		new(0x08, "Deep water"),
		new(0x09, "Shallow water"),
		new(0x0A, "Short water ladder"),
		new(0x0B, "Collision (weird deep water in Overworld)"),
		new(0x0C, "Overlay mask"),
		new(0x0D, "Spike floor"),
		new(0x0E, "GT ice"),
		new(0x0F, "Ice palace ice"),
		new(0x10, "Slope ◤"),
		new(0x11, "Slope ◥"),
		new(0x12, "Slope ◣"),
		new(0x13, "Slope ◢"),
		new(0x14, "Nothing"),
		new(0x15, "Nothing"),
		new(0x16, "Nothing"),
		new(0x17, "Nothing"),
		new(0x18, "Slope ◤"),
		new(0x19, "Slope ◥"),
		new(0x1A, "Slope ◣"),
		new(0x1B, "Slope ◢"),
		new(0x1C, "Layer 2 overlay"),
		new(0x1D, "North single-layer auto stairs"),
		new(0x1E, "North layer-swap auto stairs"),
		new(0x1F, "North layer-swap auto stairs"),
		new(0x20, "Pit"),
		new(0x21, "Nothing"),
		new(0x22, "Manual stairs"),
		new(0x23, "Pot switch"),
		new(0x24, "Pressure switch"),
		new(0x25, "Nothing (unused but referenced by somaria blocks)"),
		new(0x26, "Collision (near stairs?)"),
		new(0x27, "Hookshottable object"),
		new(0x28, "North ledge"),
		new(0x29, "South ledge"),
		new(0x2A, "East ledge"),
		new(0x2B, "West ledge"),
		new(0x2C, "◤ ledge"),
		new(0x2D, "◣ ledge"),
		new(0x2E, "◥ ledge"),
		new(0x2F, "◢ ledge"),
		new(0x30, "Straight inter-room stairs south/up 0"),
		new(0x31, "Straight inter-room stairs south/up 1"),
		new(0x32, "Straight inter-room stairs south/up 2"),
		new(0x33, "Straight inter-room stairs south/up 3"),
		new(0x34, "Straight inter-room stairs north/down 0"),
		new(0x35, "Straight inter-room stairs north/down 1"),
		new(0x36, "Straight inter-room stairs north/down 2"),
		new(0x37, "Straight inter-room stairs north/down 3"),
		new(0x38, "Straight inter-room stairs north/down edge"),
		new(0x39, "Straight inter-room stairs south/up edge"),
		new(0x3A, "Star tile (inactive on load)"),
		new(0x3B, "Star tile (active on load)"),
		new(0x3C, "Nothing"),
		new(0x3D, "South single-layer auto stairs"),
		new(0x3E, "South layer-swap auto stairs"),
		new(0x3F, "South layer-swap auto stairs"),
		new(0x40, "Thick grass"),
		new(0x41, "Nothing"),
		new(0x42, "Gravestone"),
		new(0x43, "Skull Woods entrance"),
		new(0x44, "Spike"),
		new(0x45, "Nothing"),
		new(0x46, "Desert Tablet"),
		new(0x47, "Nothing"),
		new(0x48, "Diggable ground"),
		new(0x49, "Nothing"),
		new(0x4A, "Diggable ground"),
		new(0x4B, "Warp tile"),
		new(0x4C, "Nothing / Overworld square corner"),
		new(0x4D, "Nothing / Overworld square corner"),
		new(0x4E, "Nothing / Overworld square corner"),
		new(0x4F, "Nothing / Overworld square corner"),
		new(0x50, "Green bush"),
		new(0x51, "Dark bush"),
		new(0x52, "Gray rock"),
		new(0x53, "Black rock"),
		new(0x54, "Hint tile/Sign"),
		new(0x55, "Big gray rock"),
		new(0x56, "Big black rock"),
		new(0x57, "Bonk rocks"),
		new(0x58, "Chest 0"),
		new(0x59, "Chest 1"),
		new(0x5A, "Chest 2"),
		new(0x5B, "Chest 3"),
		new(0x5C, "Chest 4"),
		new(0x5D, "Chest 5"),
		new(0x5E, "Spiral stairs"),
		new(0x5F, "Spiral stairs"),
		new(0x60, "Rupee tile"),
		new(0x61, "Nothing"),
		new(0x62, "Bombable floor"),
		new(0x63, "Minigame chest"),
		new(0x64, "Nothing"),
		new(0x65, "Nothing"),
		new(0x66, "Crystal peg down"),
		new(0x67, "Crystal peg up"),
		new(0x68, "Upwards conveyor"),
		new(0x69, "Downwards conveyor"),
		new(0x6A, "Leftwards conveyor"),
		new(0x6B, "Rightwards conveyor"),
		new(0x6C, "North vines"),
		new(0x6D, "South vines"),
		new(0x6E, "West vines"),
		new(0x6F, "East vines"),
		new(0x70, "Pot/Hammer peg/Push block 00"),
		new(0x71, "Pot/Hammer peg/Push block 01"),
		new(0x72, "Pot/Hammer peg/Push block 02"),
		new(0x73, "Pot/Hammer peg/Push block 03"),
		new(0x74, "Pot/Hammer peg/Push block 04"),
		new(0x75, "Pot/Hammer peg/Push block 05"),
		new(0x76, "Pot/Hammer peg/Push block 06"),
		new(0x77, "Pot/Hammer peg/Push block 07"),
		new(0x78, "Pot/Hammer peg/Push block 08"),
		new(0x79, "Pot/Hammer peg/Push block 09"),
		new(0x7A, "Pot/Hammer peg/Push block 0A"),
		new(0x7B, "Pot/Hammer peg/Push block 0B"),
		new(0x7C, "Pot/Hammer peg/Push block 0C"),
		new(0x7D, "Pot/Hammer peg/Push block 0D"),
		new(0x7E, "Pot/Hammer peg/Push block 0E"),
		new(0x7F, "Pot/Hammer peg/Push block 0F"),
		new(0x80, "North/South door"),
		new(0x81, "East/West door"),
		new(0x82, "North/South shutter door"),
		new(0x83, "East/West shutter door"),
		new(0x84, "North/South layer 2 door"),
		new(0x85, "East/West layer 2 door"),
		new(0x86, "North/South layer 2 shutter door"),
		new(0x87, "East/West layer 2 shutter door"),
		new(0x88, "Some type of door (?)"),
		new(0x89, "East/West transport door"),
		new(0x8A, "Some type of door (?)"),
		new(0x8B, "Some type of door (?)"),
		new(0x8C, "Some type of door (?)"),
		new(0x8D, "Some type of door (?)"),
		new(0x8E, "Entrance door"),
		new(0x8F, "Entrance door"),
		new(0x90, "Layer toggle shutter door (?)"),
		new(0x91, "Layer toggle shutter door (?)"),
		new(0x92, "Layer toggle shutter door (?)"),
		new(0x93, "Layer toggle shutter door (?)"),
		new(0x94, "Layer toggle shutter door (?)"),
		new(0x95, "Layer toggle shutter door (?)"),
		new(0x96, "Layer toggle shutter door (?)"),
		new(0x97, "Layer toggle shutter door (?)"),
		new(0x98, "Layer+Dungeon toggle shutter door (?)"),
		new(0x99, "Layer+Dungeon toggle shutter door (?)"),
		new(0x9A, "Layer+Dungeon toggle shutter door (?)"),
		new(0x9B, "Layer+Dungeon toggle shutter door (?)"),
		new(0x9C, "Layer+Dungeon toggle shutter door (?)"),
		new(0x9D, "Layer+Dungeon toggle shutter door (?)"),
		new(0x9E, "Layer+Dungeon toggle shutter door (?)"),
		new(0x9F, "Layer+Dungeon toggle shutter door (?)"),
		new(0xA0, "North/South Dungeon swap door"),
		new(0xA1, "Dungeon toggle door (?)"),
		new(0xA2, "Dungeon toggle door (?)"),
		new(0xA3, "Dungeon toggle door (?)"),
		new(0xA4, "Dungeon toggle door (?)"),
		new(0xA5, "Dungeon toggle door (?)"),
		new(0xA6, "Nothing"),
		new(0xA7, "Nothing"),
		new(0xA8, "Layer+Dungeon toggle shutter door (?)"),
		new(0xA9, "Layer+Dungeon toggle shutter door (?)"),
		new(0xAA, "Layer+Dungeon toggle shutter door (?)"),
		new(0xAB, "Layer+Dungeon toggle shutter door (?)"),
		new(0xAC, "Layer+Dungeon toggle shutter door (?)"),
		new(0xAD, "Layer+Dungeon toggle shutter door (?)"),
		new(0xAE, "Layer+Dungeon toggle shutter door (?)"),
		new(0xAF, "Layer+Dungeon toggle shutter door (?)"),
		new(0xB0, "Somaria ─"),
		new(0xB1, "Somaria │"),
		new(0xB2, "Somaria ┌"),
		new(0xB3, "Somaria └"),
		new(0xB4, "Somaria ┐"),
		new(0xB5, "Somaria ┘"),
		new(0xB6, "Somaria ⍰ 1 way"),
		new(0xB7, "Somaria ┬"),
		new(0xB8, "Somaria ┴"),
		new(0xB9, "Somaria ├"),
		new(0xBA, "Somaria ┤"),
		new(0xBB, "Somaria ┼"),
		new(0xBC, "Somaria ⍰ 2 way"),
		new(0xBD, "Somaria ┼ crossover"),
		new(0xBE, "Pipe entrance"),
		new(0xBF, "Nothing"),
		new(0xC0, "Torch 00"),
		new(0xC1, "Torch 01"),
		new(0xC2, "Torch 02"),
		new(0xC3, "Torch 03"),
		new(0xC4, "Torch 04"),
		new(0xC5, "Torch 05"),
		new(0xC6, "Torch 06"),
		new(0xC7, "Torch 07"),
		new(0xC8, "Torch 08"),
		new(0xC9, "Torch 09"),
		new(0xCA, "Torch 0A"),
		new(0xCB, "Torch 0B"),
		new(0xCC, "Torch 0C"),
		new(0xCD, "Torch 0D"),
		new(0xCE, "Torch 0E"),
		new(0xCF, "Torch 0F"),
		new(0xD0, "Nothing"),
		new(0xD1, "Nothing"),
		new(0xD2, "Nothing"),
		new(0xD3, "Nothing"),
		new(0xD4, "Nothing"),
		new(0xD5, "Nothing"),
		new(0xD6, "Nothing"),
		new(0xD7, "Nothing"),
		new(0xD8, "Nothing"),
		new(0xD9, "Nothing"),
		new(0xDA, "Nothing"),
		new(0xDB, "Nothing"),
		new(0xDC, "Nothing"),
		new(0xDD, "Nothing"),
		new(0xDE, "Nothing"),
		new(0xDF, "Nothing"),
		new(0xE0, "Nothing"),
		new(0xE1, "Nothing"),
		new(0xE2, "Nothing"),
		new(0xE3, "Nothing"),
		new(0xE4, "Nothing"),
		new(0xE5, "Nothing"),
		new(0xE6, "Nothing"),
		new(0xE7, "Nothing"),
		new(0xE8, "Nothing"),
		new(0xE9, "Nothing"),
		new(0xEA, "Nothing"),
		new(0xEB, "Nothing"),
		new(0xEC, "Nothing"),
		new(0xED, "Nothing"),
		new(0xEE, "Nothing"),
		new(0xEF, "Nothing"),
		new(0xF0, "Door 0 bottom"),
		new(0xF1, "Door 1 bottom"),
		new(0xF2, "Door 2 bottom"),
		new(0xF3, "Door 3 bottom"),
		new(0xF4, "Door X bottom? (unused?)"),
		new(0xF5, "Door X bottom? (unused?)"),
		new(0xF6, "Door X bottom? (unused?)"),
		new(0xF7, "Door X bottom? (unused?)"),
		new(0xF8, "Door 0 top"),
		new(0xF9, "Door 1 top"),
		new(0xFA, "Door 2 top"),
		new(0xFB, "Door 3 top"),
		new(0xFC, "Door X top? (unused?)"),
		new(0xFD, "Door X top? (unused?)"),
		new(0xFE, "Door X top? (unused?)"),
		new(0xFF, "Door X top? (unused?)")
	};

}
