using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZeldaFullEditor
{
    public class Room_Name
    {

        public string[] room_name = new string[]{
            "Room $00  Ganon","Room $01  Hyrule Castle (North Corridor)","Room $02  Hyrule Castle (Switch Room)",
            "Room $03  Houlihan Room","Room $04  Turtle Rock (Crysta-roller Room)",
            "Room $05  Empty Clone Room","Room $06  Swamp Palace (Arrghus[Boss])",
            "Room $07  Tower of Hera (Moldorm[Boss])","Room $08  Cave (Healing Fairy)","Room $09  Palace of Darkness",
            "Room $0A  Palace of Darkness (Stalfos Trap Room)","Room $0B  Palace of Darkness (Turtle Room)","Room $0C  Ganon's Tower (Entrance Room)",
            "Room $0D  Ganon's Tower (Agahnim2[Boss])","Room $0E  Ice Palace (Entrance Room)","Room $0F  Empty Clone Room",
            "Room $10  Ganon Evacuation Route","Room $11  Hyrule Castle (Bombable Stock Room)",
            "Room $12  Sanctuary","Room $13  Turtle Rock (Hokku-Bokku Key Room 2)","Room $14  Turtle Rock (Big Key Room)",
            "Room $15  Turtle Rock","Room $16  Swamp Palace (Swimming Treadmill)","Room $17  Tower of Hera (Moldorm Fall Room)",
            "Room $18  Cave","Room $19  Palace of Darkness (Dark Maze)","Room $1A  Palace of Darkness (Big Chest Room)",
            "Room $1B  Palace of Darkness (Mimics / Moving Wall Room)","Room $1C  Ganon's Tower (Ice Armos)","Room $1D  Ganon's Tower (Final Hallway)",
            "Room $1E  Ice Palace (Bomb Floor / Bari Room)","Room $1F  Ice Palace (Pengator / Big Key Room)","Room $20  Agahnim's Tower (Agahnim[Boss])",
            "Room $21  Hyrule Castle (Key-rat Room)","Room $22  Hyrule Castle (Sewer Text Trigger Room)","Room $23  Turtle Rock (West Exit to Balcony)",
            "Room $24  Turtle Rock (Double Hokku-Bokku / Big chest Room)","Room $25  Empty Clone Room","Room $26  Swamp Palace (Statue Room)",
            "Room $27  Tower of Hera (Big Chest)","Room $28  Swamp Palace (Entrance Room)","Room $29  Skull Woods (Mothula[Boss])",
            "Room $2A  Palace of Darkness (Big Hub Room)","Room $2B  Palace of Darkness (Map Chest / Fairy Room)","Room $2C  Cave",
            "Room $2D  Empty Clone Room","Room $2E  Ice Palace (Compass Room)","Room $2F  Cave (Kakariko Well HP)",
            "Room $30  Agahnim's Tower (Maiden Sacrifice Chamber)","Room $31  Tower of Hera (Hardhat Beetles Room)","Room $32  Hyrule Castle (Sewer Key Chest Room)",
            "Room $33  Desert Palace (Lanmolas[Boss])","Room $34  Swamp Palace (Push Block Puzzle / Pre-Big Key Room)","Room $35  Swamp Palace (Big Key / BS Room)",
            "Room $36  Swamp Palace (Big Chest Room)","Room $37  Swamp Palace (Map Chest / Water Fill Room)","Room $38  Swamp Palace (Key Pot Room)",
            "Room $39  Skull Woods (Gibdo Key / Mothula Hole Room)","Room $3A  Palace of Darkness (Bombable Floor Room)",
            "Room $3B  Palace of Darkness (Spike Block / Conveyor Room)","Room $3C  Cave","Room $3D  Ganon's Tower (Torch Room 2)",
            "Room $3E  Ice Palace (Stalfos Knights / Conveyor Hellway)","Room $3F  Ice Palace (Map Chest Room)","Room $40  Agahnim's Tower (Final Bridge Room)",
            "Room $41  Hyrule Castle (First Dark Room)","Room $42  Hyrule Castle (6 Ropes Room)","Room $43  Desert Palace (Torch Puzzle / Moving Wall Room)",
            "Room $44  Thieves Town (Big Chest Room)","Room $45  Thieves Town (Jail Cells Room)","Room $46  Swamp Palace (Compass Chest Room)",
            "Room $47  Empty Clone Room","Room $48  Empty Clone Room","Room $49  Skull Woods (Gibdo Torch Puzzle Room)","Room $4A  Palace of Darkness (Entrance Room)",
            "Room $4B  Palace of Darkness (Warps / South Mimics Room)","Room $4C  Ganon's Tower (Mini-Helmasaur Conveyor Room)","Room $4D  Ganon's Tower (Moldorm Room)",
            "Room $4E  Ice Palace (Bomb-Jump Room)","Room $4F  Ice Palace Clone Room (Fairy Room)","Room $50  Hyrule Castle (West Corridor)",
            "Room $51  Hyrule Castle (Throne Room)","Room $52  Hyrule Castle (East Corridor)","Room $53  Desert Palace (Popos 2 / Beamos Hellway Room)",
            "Room $54  Swamp Palace (Upstairs Pits Room)","Room $55  Castle Secret Entrance / Uncle Death Room","Room $56  Skull Woods (Key Pot / Trap Room)",
            "Room $57  Skull Woods (Big Key Room)","Room $58  Skull Woods (Big Chest Room)","Room $59  Skull Woods (Final Section Entrance Room)",
            "Room $5A  Palace of Darkness (Helmasaur King[Boss])","Room $5B  Ganon's Tower (Spike Pit Room)","Room $5C  Ganon's Tower (Ganon-Ball Z)",
            "Room $5D  Ganon's Tower (Gauntlet 1/2/3)","Room $5E  Ice Palace (Lonely Firebar)","Room $5F  Ice Palace (Hidden Chest / Spike Floor Room)",
            "Room $60  Hyrule Castle (West Entrance Room)","Room $61  Hyrule Castle (Main Entrance Room)","Room $62  Hyrule Castle (East Entrance Room)",
            "Room $63  Desert Palace (Final Section Entrance Room)","Room $64  Thieves Town (West Attic Room)","Room $65  Thieves Town (East Attic Room)",
            "Room $66  Swamp Palace (Hidden Chest / Hidden Door Room)","Room $67  Skull Woods (Compass Chest Room)","Room $68  Skull Woods (Key Chest / Trap Room)",
            "Room $69  Empty Clone Room","Room $6A  Palace of Darkness (Rupee Room)","Room $6B  Ganon's Tower (Mimics Rooms)","Room $6C  Ganon's Tower (Lanmolas Room)",
            "Room $6D  Ganon's Tower (Gauntlet 4/5)","Room $6E  Ice Palace (Pengators Room)","Room $6F  Empty Clone Room","Room $70  Hyrule Castle (Small Corridor to Jail Cells)",
            "Room $71  Hyrule Castle (Boomerang Chest Room)","Room $72  Hyrule Castle (Map Chest Room)","Room $73  Desert Palace (Big Chest Room)",
            "Room $74  Desert Palace (Map Chest Room)","Room $75  Desert Palace (Big Key Chest Room)","Room $76  Swamp Palace (Water Drain Room)",
            "Room $77  Tower of Hera (Entrance Room)","Room $78  Empty Clone Room","Room $79  Empty Clone Room","Room $7A  Empty Clone Room",
            "Room $7B  Ganon's Tower","Room $7C  Ganon's Tower (East Side Collapsing Bridge / Exploding Wall Room)","Room $7D  Ganon's Tower (Winder / Warp Maze Room)",
            "Room $7E  Ice Palace (Hidden Chest / Bombable Floor Room)","Room $7F  Ice Palace ( Big Spike Traps Room)","Room $80  Hyrule Castle (Jail Cell Room)",
            "Room $81  Hyrule Castle","Room $82  Hyrule Castle (Basement Chasm Room)","Room $83  Desert Palace (West Entrance Room)","Room $84  Desert Palace (Main Entrance Room)",
            "Room $85  Desert Palace (East Entrance Room)","Room $86  Empty Clone Room","Room $87  Tower of Hera (Tile Room)","Room $88  Empty Clone Room",
            "Room $89  Eastern Palace (Fairy Room)","Room $8A  Empty Clone Room","Room $8B  Ganon's Tower (Block Puzzle / Spike Skip / Map Chest Room)",
            "Room $8C  Ganon's Tower (East and West Downstairs / Big Chest Room)","Room $8D  Ganon's Tower (Tile / Torch Puzzle Room)","Room $8E  Ice Palace",
            "Room $8F  Empty Clone Room","Room $90  Misery Mire (Vitreous[Boss])","Room $91  Misery Mire (Final Switch Room)","Room $92  Misery Mire (Dark Bomb Wall / Switches Room)",
            "Room $93  Misery Mire (Dark Cane Floor Switch Puzzle Room)","Room $94  Empty Clone Room","Room $95  Ganon's Tower (Final Collapsing Bridge Room)",
            "Room $96  Ganon's Tower (Torches 1 Room)","Room $97  Misery Mire (Torch Puzzle / Moving Wall Room)","Room $98  Misery Mire (Entrance Room)",
            "Room $99  Eastern Palace (Eyegore Key Room)","Room $9A  Empty Clone Room","Room $9B  Ganon's Tower (Many Spikes / Warp Maze Room)",
            "Room $9C  Ganon's Tower (Invisible Floor Maze Room)","Room $9D  Ganon's Tower (Compass Chest / Invisible Floor Room)",
            "Room $9E  Ice Palace (Big Chest Room)","Room $9F  Ice Palace","Room $A0  Misery Mire (Pre-Vitreous Room)","Room $A1  Misery Mire (Fish Room)",
            "Room $A2  Misery Mire (Bridge Key Chest Room)","Room $A3  Misery Mire","Room $A4  Turtle Rock (Trinexx[Boss])","Room $A5  Ganon's Tower (Wizzrobes Rooms)",
            "Room $A6  Ganon's Tower (Moldorm Fall Room)","Room $A7  Tower of Hera (Fairy Room)","Room $A8  Eastern Palace (Stalfos Spawn Room)",
            "Room $A9  Eastern Palace (Big Chest Room)","Room $AA  Eastern Palace (Map Chest Room)","Room $AB  Thieves Town (Moving Spikes / Key Pot Room)",
            "Room $AC  Thieves Town (Blind The Thief[Boss])","Room $AD  Empty Clone Room","Room $AE  Ice Palace","Room $AF  Ice Palace (Ice Bridge Room)",
            "Room $B0  Agahnim's Tower (Circle of Pots)","Room $B1  Misery Mire (Hourglass Room)","Room $B2  Misery Mire (Slug Room)",
            "Room $B3  Misery Mire (Spike Key Chest Room)","Room $B4  Turtle Rock (Pre-Trinexx Room)","Room $B5  Turtle Rock (Dark Maze)",
            "Room $B6  Turtle Rock (Chain Chomps Room)","Room $B7  Turtle Rock (Map Chest / Key Chest / Roller Room)","Room $B8  Eastern Palace (Big Key Room)",
            "Room $B9  Eastern Palace (Lobby Cannonballs Room)","Room $BA  Eastern Palace (Dark Antifairy / Key Pot Room)","Room $BB  Thieves Town (Hellway)","Room $BC  Thieves Town (Conveyor Toilet)",
            "Room $BD  Empty Clone Room","Room $BE  Ice Palace (Block Puzzle Room)","Room $BF  Ice Palace Clone Room (Switch Room)",
            "Room $C0  Agahnim's Tower (Dark Bridge Room)","Room $C1  Misery Mire (Compass Chest / Tile Room)","Room $C2  Misery Mire (Big Hub Room)",
            "Room $C3  Misery Mire (Big Chest Room)","Room $C4  Turtle Rock (Final Crystal Switch Puzzle Room)","Room $C5  Turtle Rock (Laser Bridge)",
            "Room $C6  Turtle Rock","Room $C7  Turtle Rock (Torch Puzzle)","Room $C8  Eastern Palace (Armos Knights[Boss])","Room $C9  Eastern Palace (Entrance Room)",
            "Room $CA  ??","Room $CB  Thieves Town (North West Entrance Room)","Room $CC  Thieves Town (North East Entrance Room)",
            "Room $CD  Empty Clone Room","Room $CE  Ice Palace (Hole to Kholdstare Room)","Room $CF  Empty Clone Room","Room $D0  Agahnim's Tower (Dark Maze)",
            "Room $D1  Misery Mire (Conveyor Slug / Big Key Room)","Room $D2  Misery Mire (Mire02 / Wizzrobes Room)","Room $D3  Empty Clone Room","Room $D4  Empty Clone Room",
            "Room $D5  Turtle Rock (Laser Key Room)","Room $D6  Turtle Rock (Entrance Room)","Room $D7  Empty Clone Room","Room $D8  Eastern Palace (Zeldagamer Room / Pre-Armos Knights Room)",
            "Room $D9  Eastern Palace (Canonball Room","Room $DA  Eastern Palace","Room $DB  Thieves Town (Main (South West) Entrance Room)",
            "Room $DC  Thieves Town (South East Entrance Room)","Room $DD  Empty Clone Room","Room $DE  Ice Palace (Kholdstare[Boss])",
            "Room $DF  Cave","Room $E0  Agahnim's Tower (Entrance Room)","Room $E1  Cave (Lost Woods HP)","Room $E2  Cave (Lumberjack's Tree HP)",
            "Room $E3  Cave (1/2 Magic)","Room $E4  Cave (Lost Old Man Final Cave)","Room $E5  Cave (Lost Old Man Final Cave)",
            "Room $E6  Cave","Room $E7  Cave","Room $E8  Cave","Room $E9  Empty Clone Room","Room $EA  Cave (Spectacle Rock HP)",
            "Room $EB  Cave","Room $EC  Empty Clone Room","Room $ED  Cave","Room $EE  Cave (Spiral Cave)","Room $EF  Cave (Crystal Switch / 5 Chests Room)",
            "Room $F0  Cave (Lost Old Man Starting Cave)","Room $F1  Cave (Lost Old Man Starting Cave)","Room $F2  House","Room $F3  House (Old Woman (Sahasrahla's Wife?))",
            "Room $F4  House (Angry Brothers)","Room $F5  House (Angry Brothers)","Room $F6  Empty Clone Room","Room $F7  Empty Clone Room",
            "Room $F8  Cave","Room $F9  Cave","Room $FA  Cave","Room $FB  Cave","Room $FC  Empty Clone Room","Room $FD  Cave",
            "Room $FE  Cave","Room $FF  Cave",

            "Room $100  Chest  Minigame","Room $101  Houses","Room $102  Sick Boy house","Room $103  Tavern","Room $104  Link's House","Room $105  Sarashrala Hut","Room $106  Chest Minigame","Room $107  Library",
            "Room $108  Chicken House","Room $109  Witch Shop","Room $10A  Aginah's Cave","Room $10B  Dam","Room $10C  Mimic Cave","Room $10D  Mire Shed","Room $10E  Cave","Room $10F  Shop","Room $110  Shop",
            "Room $111  Archery Minigame","Room $112  DW Church/Shop","Room $113  Grave Cave","Room $114  Fairy Fountain","Room $115  Fairy Upgrade","Room $116  Pyramid Fairy","Room $117  Spike Cave",
            "Room $118  Chest Minigame","Room $119  Blind Hut","Room $11A  Bonzai Cave","Room $11B  Circle of bush Cave","Room $11C  Big Bomb Shop, C-House","Room $11D  Blind Hut 2","Room $11E  Hype Cave",
            "Room $11F  Shop","Room $120  Ice Cave","Room $121  Smith","Room $122  Fortune Teller","Room $123  MiniMoldorm Cave","Room $124  Under Rock Caves","Room $125  Smith","Room $126  Cave","Room $127  Mazeblock Cave",
            "Room $128  Smith Peg Cave"
        };
    }
}
