using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZeldaFullEditor
{
    public static class Sprite_SubsetNames
    {
        public static string[] names = new string[]
        {
            "?","?","?","?","?","?","?","?","?","?","?","?",
            "12:Octorock,O.Balloon,Crab,Fire. Zora",
            "13:Taros",
            "14:Thief,Poe",
            "15:Bush Crab",
            "16:Tektite,Deadrock,Armos",
            "17:Bunny?,Raven,Buzzblob,Fake MS",
            "18:Vulture,Jazzhand,Tablet",
            "19:Trainee Guard",
            "20:Lynel",
            "21:DW Thief,Chicken,PurpleChest",
            "22:Hinox,SnapDragon1",
            "23:Moblin,SnapDragon2",
            "24:Octorok,Fire.Zora",
            "25:Dacto,Swamola,Kiki",
            "26:Agahnim/Ganon",
            "27:Zirro,Pickit",
            "28:Keese,Rope,Rat,Oldman",
            "29:Armos Knight",
            "30:MiniHelma,Beetle,MiniMoldorm",
            "31:Stalfos,Bari,Spark,Flamme",
            "32:Stalfos Knight,Slime,Babusu",
            "33:Ganon1",
            "34:Water Tektite,Pirogusu,Kyameron",
            "35:Gibdo, WallMaster",
            "36:Eyebat,Grasshopper,Skullrope",
            "37:Sluggula,Spark,Wizzrobes",
            "38:Pendator,Freezor",
            "39:HokkuBokku,Chain Chomp,Roller,Somaria",
            "40:Zazak,Gibo",
            "41:Skullrobes, Falling moblin",
            "42:Kodongo,Terrorpin",
            "43:??",
            "44:Popo,Mimic,Beamos",
            "45:Ending Stuff",
            "46:CanonBalls,Eyegores",
            "47:Canons,Leever",
            "48:Moldorm(Boss)",
            "49:Lanmolas",
            "50:TitleScreen Sword",
            "51:Ganon2/Falling tiles",
            "52:Ending Npcs",
            "53:Ending Npcs",
            "54:Ending Npcs",
            "55:Hobo",
            "56:Mothula(Boss)",
            "57:Arrghus(Boss)",
            "58:Helmasaure1(Boss)",
            "59:Blind(Boss)",
            "60:Kholdstare(Boss)",
            "61:Vitreous(Boss)",
            "62:Helmasaure2(Boss)",
            "63:Trinexx1",
            "64:Trinexx2",
            "65:Ganon3",
            "66:Agahnim1",
            "67:Agahnim2",
            "68:Walking Zora, Zora King",
            "69:Ganon4",
            "70:Chainball/Canon Guard",
            "71:Priest/Mantle",
            "72:Archer,TutorialSoldier",
            "73:Various Guards",
            "74:Npcs",
            "75:Npc",
            "76:Witch,Sarashrala",
            "77:Smith,Npcs",
            "78:Animals",
            "79:Npcs",
            "80:Npcs/Chicken",
            "81:Uncle,Sick Kid",
            "82:Statue,Spikes,Switches,Antifairy",
            "83:Statue,Spikes,Switches,Antifairy",
            "84:Falling Block",
            "85:Agahnim3",
            "86:Map parts",
            "87:Map parts",
            "88:Swag Duck,Chest,ect",
            "89:Follower kiki,sign dude",
            "90:Items",
            "91:Items",
            "92:Items",
            "93:Items/Ending Stuff",
            "94:Sword",
            "95:Shield"
        };
    }
}
