namespace ZeldaFullEditor
{
    public static class Sprite_SubsetNames
    {
        public static string[] names = new string[]
        {
            "?",
            "?",
            "?",
            "?",
            "?",
            "?",
            "?",
            "?",
            "?",
            "?",
            "?",
            "?",
            "12:Octorok,O.Balloon,Crab,Fire. Zora",
            "13:Taros",
            "14:Thief,Poe",
            "15:Hoarder",
            "16:Tektite,Deadrock,Armos",
            "17:Toppo,Raven,Buzzblob,Fake MS",
            "18:Vulture,Geldman,Tablet",
            "19:Knife Guard",
            "20:Lynel",
            "21:DW Thief,Cucco,PurpleChest",
            "22:Hinox,Snapdragon 1",
            "23:Moblin,Snapdragon 2",
            "24:Octorok,Zora",
            "25:Dacto,Swamola,Kiki",
            "26:Agahnim/Ganon",
            "27:Zirro,Pikit",
            "28:Keese,Rope,Rat,Old Man",
            "29:Armos Knight",
            "30:MiniHelma,Beetle,MiniMoldorm",
            "31:Stalfos,Bari,Spark",
            "32:Stalfos Knight,Zol,Babusu",
            "33:Ganon 1",
            "34:Hover,Pirogusu,Kyameron",
            "35:Gibdo, Wallmaster",
            "36:Eyebat,Cricket,Stalrope",
            "37:Sluggula,Spark,Wizzrobe",
            "38:Pengator,Freezor",
            "39:Pokey,Chainchomp,Roller,Somaria",
            "40:Zazak,Gibo",
            "41:Skullrobe, Falling bull",
            "42:Kodongo,Terrorpin",
            "43:??",
            "44:Popo,Mimic,Beamos",
            "45:Ending Stuff",
            "46:Cannonball,Eyegore",
            "47:Cannon,Leever",
            "48:Moldorm (Boss)",
            "49:Lanmolas",
            "50:Intro Sword",
            "51:Ganon 2/Falling tile",
            "52:Epilogue NPCs",
            "53:Epilogue NPCs",
            "54:Epilogue NPCs",
            "55:Hobo",
            "56:Mothula (Boss)",
            "57:Arrghus (Boss)",
            "58:Helmasaur 1 (Boss)",
            "59:Blind (Boss)",
            "60:Kholdstare (Boss)",
            "61:Vitreous (Boss)",
            "62:Helmasaur 2 (Boss)",
            "63:Trinexx 1",
            "64:Trinexx 2",
            "65:Ganon 3",
            "66:Agahnim 1",
            "67:Agahnim 2",
            "68:Walking Zora, Zora King",
            "69:Ganon 4",
            "70:BallNChain/Cannon Guard",
            "71:Priest/Mantle",
            "72:Archer,Tutorial Guard",
            "73:Guards",
            "74:NPCs",
            "75:NPC",
            "76:Witch,Sahasrahla",
            "77:Smith,NPCs",
            "78:Animals",
            "79:NPCs",
            "80:NPCs/Cucco",
            "81:Uncle,Sick Kid",
            "82:Statue,Spikes,Switches,Antifairy",
            "83:Statue,Spikes,Switches,Antifairy",
            "84:Falling block",
            "85:Agahnim 3",
            "86:Dungeon map",
            "87:Dungeon map",
            "88:Duck,Chest,etc",
            "89:Follower kiki,Picklock",
            "90:Items",
            "91:Items",
            "92:Items",
            "93:Items/Epilogue",
            "94:Sword",
            "95:Shield",
        };
    }
}
