<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>ZScream</AssemblyName>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishUrl>C:\Users\adamo\Desktop\zscream\ZS3.2.4Beta\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>false</MapFileExtensions>
    <OpenBrowserOnPublish>false</OpenBrowserOnPublish>
    <ApplicationRevision>7</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);SYSLIB0011;WFO1000</NoWarn>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>bin\Release\Version3.2.4\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>ZeldaFullEditor.Program</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>screamlink.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>04C489A2A4F503757F45568FA161B416C2E6D403</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>ZeldaFullEditor_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>false</SignManifests>
  </PropertyGroup>
  <PropertyGroup>
    <TargetZone>LocalIntranet</TargetZone>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" />
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Gui\DamageClassControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\ExtraForms\Chestviewer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\CustomPanel.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Gui\CustomTabControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\CGRamViewer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\ExtraForms\PrizePackBox.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\DungeonViewer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\GfxEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\GfxGroupsForm.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\GfxImportExport.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\MusicEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\NamesEditorForm.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\NamesEditorFormFile.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\ObjectDesigner.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\OverworldEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\PrizePacksEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\ScreenEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\SpriteEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\PaletteEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\VramViewer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\WindowPanel.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\ObjectViewer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\Scene\SceneOW.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Gui\Scene\SceneUW.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Gui\Scene\SceneBase.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="SpritesView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Gui\MainTabs\TextEditor.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <None Include=".editorconfig" />
    <None Update="GfxSheetExpanded.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ScratchPad.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="ZCompressLibrary.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="zelda3compression.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="asar.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="CustomCollision.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="debug.asm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="DefaultNames.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="expandedEntrances.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="HardwareRegisters.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="newgraves.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="PatchNotes.txt" />
    <Content Include="Resources\damageclass.png" />
    <Content Include="ZS ROM MAP.txt" />
    <Content Include="ZS_Patches\Hex Edits\Misc Small Patches.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Items\AST Boots.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Misc\Big Bomb Requirements.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Misc\HoleOverlayFix.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Misc\IntroSkip.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Misc\JP1.0 Glitches.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Misc\Link Bed Start Position.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Misc\NoRocks.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Misc\Rainstate Skip.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Misc\TorchTags.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Misc\Weathervane.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Music\LostWoodsExitMusic.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Npcs\Bottle Vendor.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Sprites\Crystalswitch Conveyor.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Sprites\Elemental Trinexx.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Sprites\Eye Lasers Active.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Sprites\Khodstare Speeds.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Sprites\Spike Damage.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Sprites\Spikes_Subtype.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZS_Patches\Version.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ZSCustomOverworld.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="spritesmove.asm">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="screamlink.ico" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.5.2">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.5.2 %28x86 et x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="ZS_Patches\UNPATCHED\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Lidgren.Network" Version="1.0.2" />
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="ZScreamer.cs" />
    <Compile Remove="Utility\ZeldaException.cs" />
    <Compile Remove="Utility\Utils.cs" />
    <Compile Remove="Utility\UIText.cs" />
    <Compile Remove="Utility\UIColors.cs" />
    <Compile Remove="Utility\Structs\TilemapPosition.cs" />
    <Compile Remove="Utility\Structs\Tile32.cs" />
    <Compile Remove="Utility\Structs\Tile16.cs" />
    <Compile Remove="Utility\Structs\Tile.cs" />
    <Compile Remove="Utility\Structs\ROMAddress.cs" />
    <Compile Remove="Utility\Structs\OAMTile.cs" />
    <Compile Remove="Utility\Structs\OAMDrawInfo.cs" />
    <Compile Remove="Utility\Structs\DrawInfo.cs" />
    <Compile Remove="Utility\Sprite_SubsetNames.cs" />
    <Compile Remove="Utility\SNESFunctions.cs" />
    <Compile Remove="Utility\Palettes.cs" />
    <Compile Remove="Utility\IntFunctions.cs" />
    <Compile Remove="Utility\Interfaces\ITypeID.cs" />
    <Compile Remove="Utility\Interfaces\ITilesTableBasedDraw.cs" />
    <Compile Remove="Utility\Interfaces\IMultilayered.cs" />
    <Compile Remove="Utility\Interfaces\IMouseCollidable.cs" />
    <Compile Remove="Utility\Interfaces\IFreelyPlaceable.cs" />
    <Compile Remove="Utility\Interfaces\IDrawableSprite.cs" />
    <Compile Remove="Utility\Interfaces\IDelegatedDraw.cs" />
    <Compile Remove="Utility\Interfaces\IByteable.cs" />
    <Compile Remove="Utility\Interfaces\DungeonObject.cs" />
    <Compile Remove="Utility\Enums\Worldiness.cs" />
    <Compile Remove="Utility\Enums\TextView.cs" />
    <Compile Remove="Utility\Enums\SpriteCategory.cs" />
    <Compile Remove="Utility\Enums\SpecialObjectType.cs" />
    <Compile Remove="Utility\Enums\RoomObjectCategory.cs" />
    <Compile Remove="Utility\Enums\Lizard.cs" />
    <Compile Remove="Utility\Enums\DungeonObjectSizeability.cs" />
    <Compile Remove="Utility\Enums\DungeonObjectSet.cs" />
    <Compile Remove="Utility\Enums\DungeonLimits.cs" />
    <Compile Remove="Utility\Enums\DoorDirection.cs" />
    <Compile Remove="Utility\Enums\DoorCategory.cs" />
    <Compile Remove="Utility\EntityName.cs" />
    <Compile Remove="Utility\DefaultEntities.cs" />
    <Compile Remove="Utility\DataObjects\TilesList.cs" />
    <Compile Remove="Utility\DataObjects\Point3D.cs" />
    <Compile Remove="Utility\DataObjects\FloorNumber.cs" />
    <Compile Remove="Utility\DataObjects\DoorTilesList.cs" />
    <Compile Remove="Utility\DataObjects\AddressSet.cs" />
    <Compile Remove="Utility\Constants.cs" />
    <Compile Remove="Hacks\asar.cs" />
    <Compile Remove="Gui\Scene\SceneUWnew.cs" />
    <Compile Remove="Gui\Scene\SceneModes\UWTorchMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\UWSpriteMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\UWSecretsMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\UWLayerMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\UWEntranceMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\UWDoorMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\UWCollisionMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\UWBlockMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\SceneMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\OWTransportMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\OWTileMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\OWSpriteMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\OWSecretsMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\OWOverlayMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\OWGravesMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\OWExitMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\OWEntranceMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\OWDoorMode.cs" />
    <Compile Remove="Gui\Scene\SceneModes\ClipboardData\TileData.cs" />
    <Compile Remove="Gui\Scene\Scene.cs" />
    <Compile Remove="Gui\MainTabs\TextEditorMessages.cs" />
    <Compile Remove="Gui\ExtraForms\MessageAsBytes.Designer.cs" />
    <Compile Remove="Gui\ExtraForms\MessageAsBytes.cs" />
    <Compile Remove="Gui\ExtraForms\DictionariesForm.Designer.cs" />
    <Compile Remove="Gui\ExtraForms\DictionariesForm.cs" />
    <Compile Remove="GraphicsManager.cs" />
    <Compile Remove="GlobalSuppressions.cs" />
    <Compile Remove="DungeonData.cs" />
    <Compile Remove="Data\Underworld\RoomObjectTileLister.cs" />
    <Compile Remove="Data\Underworld\RoomObject.cs" />
    <Compile Remove="Data\Underworld\RoomLayout.cs" />
    <Compile Remove="Data\Underworld\Room.cs" />
    <Compile Remove="Data\Underworld\Entrance.cs" />
    <Compile Remove="Data\Underworld\DungeonTorch.cs" />
    <Compile Remove="Data\Underworld\DungeonSprite.cs" />
    <Compile Remove="Data\Underworld\DungeonSecret.cs" />
    <Compile Remove="Data\Underworld\DungeonRoomParts.cs" />
    <Compile Remove="Data\Underworld\DungeonRoomChestsHandler.cs" />
    <Compile Remove="Data\Underworld\DungeonRoom.cs" />
    <Compile Remove="Data\Underworld\DungeonLayout.cs" />
    <Compile Remove="Data\Underworld\DungeonDoor.cs" />
    <Compile Remove="Data\Underworld\DungeonDestination.cs" />
    <Compile Remove="Data\Underworld\DungeonChestItem.cs" />
    <Compile Remove="Data\Underworld\DungeonBlock.cs" />
    <Compile Remove="Data\Underworld\CollisionRectangle.cs" />
    <Compile Remove="Data\Types\SpriteTypes.cs" />
    <Compile Remove="Data\Types\SpriteDraw.cs" />
    <Compile Remove="Data\Types\SecretItemType.cs" />
    <Compile Remove="Data\Types\LayerMergeType.cs" />
    <Compile Remove="Data\Types\ItemReceipt.cs" />
    <Compile Remove="Data\Types\IEntityType.cs" />
    <Compile Remove="Data\Types\DungeonObjectTypes.cs" />
    <Compile Remove="Data\Types\DungeonObjectDraw.cs" />
    <Compile Remove="Data\Types\DungeonDoorType.cs" />
    <Compile Remove="Data\Types\DungeonDoorDraw.cs" />
    <Compile Remove="Data\Overworld\OverworldTransport.cs" />
    <Compile Remove="Data\Overworld\OverworldSprite.cs" />
    <Compile Remove="Data\Overworld\OverworldSecret.cs" />
    <Compile Remove="Data\Overworld\OverworldExit.cs" />
    <Compile Remove="Data\Overworld\OverworldEntrance.cs" />
    <Compile Remove="Data\Overworld\OverworldEntity.cs" />
    <Compile Remove="Data\Overworld\OverworldDestination.cs" />
    <Compile Remove="Data\Overworld\Overworld.cs" />
    <Compile Remove="Data\Overworld\OverlayData.cs" />
    <Compile Remove="Data\Overworld\Gravestone.cs" />
    <Compile Remove="Data\OverlayTile.cs" />
    <Compile Remove="Data\Misc\SpriteProperties.cs" />
    <Compile Remove="Data\Misc\OverworldMap.cs" />
    <Compile Remove="Data\Misc\MapIcon.cs" />
    <Compile Remove="Data\Misc\DungeonMap.cs" />
  </ItemGroup>
  <ItemGroup Label="EmbeddedResource items now included by globbing that were not in the original project file">
    <EmbeddedResource Remove="Gui\ExtraForms\MessageAsBytes.resx" />
    <EmbeddedResource Remove="Gui\ExtraForms\DictionariesForm.resx" />
  </ItemGroup>
</Project>